### ISSUE TITLE
Rados Striping API Support

### ISSUE THREAD

**Issue by hd916162** [ceph/go-ceph#1011]
Will there be a support for radosstriping ?
```[tasklist]
### Tasks
```

**Comment by anoopcs9** [comment]
> Will there be a support for radosstriping ?

Can you specify the corresponding API from ceph?

**Comment by hd916162** [comment]
API described here. 
src/include/radosstriper/libradosstriper.hpp
These API are also avaiable in rados cli by specify flag --striper
![image](https://github.com/user-attachments/assets/31c529d6-fb3f-4918-9175-dd161963b9fc)

**Comment by phlogistonjohn** [comment]
Thanks for the hint. I don't think the .hpp file would work for us as that is C++. But there's a `src/include/radosstriper/libradosstriper.h` that could possibly work. Please note that adding a whole new library of ceph bindings to go-ceph would be a lot of work and may not proceed quickly. Contributions and/or design discussion could speed up the process.

**Comment by phlogistonjohn** [comment]
I could see adding a new package like "rados/striper" and within it a wrapper type
`Striper` that encapsulates `rados_striper_t`. Then for example we could have methods on `Striper` for the `rados_striper_set_object_layout`* functions. And then methods like `Read`, `Write`,  `WriteFull`, etc. that are similar to what we have in rados for an `IOContext` but for `Striper` instead.  

How does that sound?

**Comment by phlogistonjohn** [comment]
I think we would skip implementing anything using `rados_striper_multi_completion_t` initially. That could be a separate future feature request once someone knows that it's really needed.
