### ISSUE TITLE
use the `client ls` command get client list filter param useless

### ISSUE THREAD

**Issue by zhaeng** [ceph/go-ceph#1018]
this is the whole command : {"prefix":"client ls","filter":["client_metadata.entity_id","1694682944885727233"]}
the result is whole that not filter by given condition `client_metadata.entity_id=1694682944885727233`

The following command executed in the shell window `ceph tell mds.cephfs.puhui-local.xyiuwq client ls "client_metadata.entity_id"="1694682944885727233` produces the expected filtered result.

So if I want to get the desired result in the code, how should I pass the filter parameter?

**Comment by phlogistonjohn** [comment]
Looks like the JSON structure should be: `{"prefix": "client ls", "filters": ["client_metadata.entity_id=1694682944885727233"]}`.
There appear to be two differences with the example you shared:
1. the key name is "filters" not "filter" (note the final s)
2. there is one single entry in the JSON array containing the filter and the value preserves the `=` between the key and value of the filter.

You also didn't say what API call you used, so I'll just double check that you're passing this JSON to `mds_command`.

**Comment by zhaeng** [comment]
> Looks like the JSON structure should be: `{"prefix": "client ls", "filters": ["client_metadata.entity_id=1694682944885727233"]}`. There appear to be two differences with the example you shared:
> 
> 1. the key name is "filters" not "filter" (note the final s)
> 2. there is one single entry in the JSON array containing the filter and the value preserves the `=` between the key and value of the filter.
> 
> You also didn't say what API call you used, so I'll just double check that you're passing this JSON to `mds_command`.

it works with command `{"prefix": "client ls", "filters": ["client_metadata.entity_id=1694682944885727233"]}`, I called MdsCommand method

**Comment by phlogistonjohn** [comment]
Great. Sounds like the question is solved. Shall we close this issue?

**Comment by zhaeng** [comment]
> Great. Sounds like the question is solved. Shall we close this issue?

Yes, Thanks ! You can close this  issue.
