### ISSUE TITLE
DiffIterate too slow for 10TB image

### ISSUE THREAD

**Issue by dinghuaming** [ceph/go-ceph#1029]
hi, i use DiffIterate to see bitmap of the image.
when the image is 10TB size, calling DiffIterate()  use about 1 hour. why?

the following is the code(imageSize = 10 *1024 * 1024 * 1024 * 1024).

	diffCfg := rbd.DiffIterateConfig{
		Offset:      0,
		Length:      imageSize,
		SnapName:    lastSnapshotName, //rbd.NoSnapshot,
		WholeObject: rbd.EnableWholeObject,
		Callback: func(offset uint64, length uint64, existData int, data interface{}) int {
			if existData < 1 {
				return 0
			}
			return 0
		},
	}

	log.Printf("[backupVolume] DiffIterate start: %v\n", util.GetNow())
	err = srcImage.DiffIterate(diffCfg)
	if err != nil {
		err = fmt.Errorf("[backupVolume] get volumeId: %s snapshotName: %s DiffIterate error: %v", srcVolumeId, lastSnapshotName, err)
		log.Println(err)
		return err
	}

	log.Printf("[backupVolume] DiffIterate end: %v\n", util.GetNow())

**Comment by phlogistonjohn** [comment]
there are a lot of factors here making this not a simple question to answer.
I would start by checking some basic parameters:
* does the performance scale linearly? IOW, does a 1TB image take 1/10th the time?
* are you using fast networks to access the cluster?
* did you compare the go code to other tools (rbd cli, etc) or languages (the equivalent code using rbd python)?
* is this time unique to this 10TB image or all 10TB images?

**Comment by dinghuaming** [comment]
hi, thanks for reply.
does the performance scale linearly? IOW, does a 1TB image take 1/10th the time?  --> no.
are you using fast networks to access the cluster?  --> yes
did you compare the go code to other tools (rbd cli, etc) or languages (the equivalent code using rbd python)? --> rbd export-diff use the same time. 
is this time unique to this 10TB image or all 10TB images? --> all 10TB image has the same problem.

**Comment by ansiwen** [comment]
> did you compare the go code to other tools (rbd cli, etc) or languages (the equivalent code using rbd python)? --> rbd export-diff use the same time.

If the rbd tool takes the same time, then ceph is just that slow, because the rbd tool is not based on this library. You would need to file that issue upstream in the ceph project, because then the bottleneck is not in our code.

**Comment by dinghuaming** [comment]
> > did you compare the go code to other tools (rbd cli, etc) or languages (the equivalent code using rbd python)? --> rbd export-diff use the same time.
> 
> If the rbd tool takes the same time, then ceph is just that slow, because the rbd tool is not based on this library. You would need to file that issue upstream in the ceph project, because then the bottleneck is not in our code.

thanks！
