### ISSUE TITLE
MacOS brew install not working as expected

### ISSUE THREAD

**Issue by GeiserX** [ceph/go-ceph#1030]
Following the instructions, the `brew install` correctly executes, and there's no error shown.

However, it's not added to PATH and If I try to find the binary, and execute it, it's missing dependencies (?)

Locations of the bins:
```
/opt/homebrew/Cellar/ceph-client/17.2.5_1.reinstall/bin/ceph
/opt/homebrew/Cellar/ceph-client/17.2.5_1.reinstall/libexec/bin/ceph
/System/Volumes/Data/opt/homebrew/Cellar/ceph-client/17.2.5_1.reinstall/bin/ceph
/System/Volumes/Data/opt/homebrew/Cellar/ceph-client/17.2.5_1.reinstall/libexec/bin/ceph
```

I'm in MacOS 15, in an M2 Pro. If I execute any of the binaries I get this dependency error: 

```
zsh: /opt/homebrew/Cellar/ceph-client/17.2.5_1.reinstall/libexec/bin/ceph: bad interpreter: /opt/homebrew/bin/python3.10: no such file or directory
```

**Comment by anoopcs9** [comment]
I don't know about MacOS and thus won't post any answer. But you'll most probably want to get in touch with the Ceph community(see [https://ceph.io/en/community/connect/)](https://ceph.io/en/community/connect/) than "go-ceph".

**Comment by GeiserX** [comment]
Hi @anoopcs9 thank for the prompt response. 

I tried installing python 3.10 via brew and now there is another error, so we're advancing a bit:

```
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/ceph-client/17.2.5_1.reinstall/libexec/bin/ceph", line 151, in <module>
    import rados
ModuleNotFoundError: No module named 'rados'
```

Shouldn't all these dependencies (python 3.10, modules) be handled by brew itself?
