### ISSUE TITLE
CI test failures on main for `TestFallocate`

### ISSUE THREAD

**Issue by anoopcs9** [ceph/go-ceph#1044]
```
=== RUN   TestFallocate/modeIsZero
    file_test.go:501: 
        	Error Trace:	/go/src/github.com/ceph/go-ceph/cephfs/file_test.go:501
        	Error:      	Received unexpected error:
        	            	cephfs: ret=-95, Operation not supported
        	Test:       	TestFallocate/modeIsZero
    file_test.go:505: 
        	Error Trace:	/go/src/github.com/ceph/go-ceph/cephfs/file_test.go:505
        	Error:      	Not equal: 
        	            	expected: int(10)
        	            	actual  : uint64(0x0)
        	Test:       	TestFallocate/modeIsZero
=== RUN   TestFallocate/increaseSize
    file_test.go:528: 
        	Error Trace:	/go/src/github.com/ceph/go-ceph/cephfs/file_test.go:528
        	Error:      	Received unexpected error:
        	            	cephfs: ret=-95, Operation not supported
        	Test:       	TestFallocate/increaseSize
    file_test.go:532: 
        	Error Trace:	/go/src/github.com/ceph/go-ceph/cephfs/file_test.go:532
        	Error:      	Not equal: 
        	            	expected: int(15)
        	            	actual  : uint64(0xa)
        	Test:       	TestFallocate/increaseSize
```

**Comment by anoopcs9** [comment]
Relevant section from https://github.com/ceph/ceph/pull/59725:

* CephFS: EOPNOTSUPP (Operation not supported ) is now returned by the CephFS fuse client for `fallocate` for the default case (i.e. mode == 0) since CephFS does not support disk space reservation. The only flags supported are `FALLOC_FL_KEEP_SIZE` and `FALLOC_FL_PUNCH_HOLE`.

**Comment by phlogistonjohn** [comment]
FWIW, I asked the ceph developer to tweak the release note because saying 'fuse client' is a bit misleading if it is impacting us. :-)

**Comment by anoopcs9** [comment]
> FWIW, I asked the ceph developer to tweak the release note because saying 'fuse client' is a bit misleading if it is impacting us. :-)

May be he missed to notice my earlier [comment](https://github.com/ceph/ceph/commit/ac34dd33099925172a7d95b267b11e6693cc5648#r148820442) where I shared the very same thought. Anyway we have a fix in the queue 😊 .

**Comment by anoopcs9** [comment]
Given that there are suggested backports, are we gonna tackle the change in API behaviour using build tags(and probably separate test file) or direct test code changes detecting the version?

**Comment by phlogistonjohn** [comment]
I have no strong opinion here, but I would prefer whatever causes the least amount of churn generally.
