### ISSUE TITLE
Add context support to RADOS functions

### ISSUE THREAD

**Issue by immesys** [ceph/go-ceph#165]
It would be really great if there was a version of IOCtx that supported a context.Context so that deadlines and cancellations could be supported. Adding a deadline externally can be done fairly easily, but actually attempting to cancel the in-flight operation is non trivial. Sometimes you initiate a write or a read on an object in an unhealthy placement group and you want to fail fast instead of blocking until the pg recovers.

I'm willing to work on this and submit a PR, but having worked with librados at only a cursory level, I'm not sure how this would work. Can someone either suggest how this could be done, or confirm that it's not possible using librados?

**Comment by phlogistonjohn** [comment]
I'd argue that this would have to be done at a higher level. While I would not be opposed to having something like that in the library I think our first job is to get coverage of the functions provided by ceph and most of those do not support timeouts when passed to the functions.

Currently, we have some [timeouts in our test code](https://github.com/ceph/go-ceph/blob/5adb049/rados/rados_test.go#L37) that make use of a goroutine. Perhaps there's a better approach but whatever that is would have to be layered on top of the ceph functions.

I would highly recommend prototyping the use of contexts in the code you have that consumes go-ceph and then we can take a look at it and then consider it, or something inspired by it, for a convenience layer in the libs.

**Comment by phlogistonjohn** [comment]
I think we can close this issue as it has been open but largely inactive for over six months. As I previously mentioned, I think this is a worthwhile suggestion but not one the core library packages ought to support directly. I hope you understand. Please feel free to reopen this if it still needs additional discussion.

**Comment by immesys** [comment]
No problem. It's not as simple as passing through some already-existing librados support for contexts/timeouts so I agree that this can be closed.
