### ISSUE TITLE
Containerized tests are failing

### ISSUE THREAD

**Issue by phlogistonjohn** [ceph/go-ceph#166]
Due to the use of Go 1.10 in the container image the image is not honoring go modules and is using the master version of testify. As of dca7be2281160d1de37dcd672efabf7595a20bc6 in testify (committed roughly 20 hours ago as of my writing)  sute.T() is returning an interface with a more limited selection of functions than the previous concrete type. Thus our rados test suite is always failng.

Since go 1.10 is two supported releases out of date I suggest we test on something supported at the very least. We may also want to look into updating the functions we call in the rados test suite for future proofing.

**Comment by nixpanic** [comment]
https://github.com/ceph/go-ceph/pull/139/commits/9840d429468f41b2406ce673d1ac7e4d6f3647f8 contains a way of using a current version of Golang.

**Comment by phlogistonjohn** [comment]
Ah, yeah I forgot about your patch but did see the wiki where that approach is mentioned.
I opted to pull the binary tarball from Go/google as it gives more precise control over what version of Go we are using. I like the idea of testing with the oldest supported version as it includes a wider pool of possible consumers of the project.

**Comment by nixpanic** [comment]
Well.... I really dislike selecting a version, and not automatically updating it. After a few months we'll be running with an unsupported golang version again. Automatically getting a new versions might break things though, so there are pros/cons for each approach. We do want to test with recent Go versions too, I guess, and keep functioning with the older ones.

**Comment by phlogistonjohn** [comment]
> Well.... I really dislike selecting a version, and not automatically updating it. After a few months we'll be running with an unsupported golang version again. 

Yup, that's a downside to this approach for sure.

> Automatically getting a new versions might break things though, so there are pros/cons for each approach. We do want to test with recent Go versions too, I guess, and keep functioning with the older ones.

Indeed. But we don't have to solve all the issues here and now.

Do you want to extract your Dockerfile patch from your PR #139 into a new PR and we can have a horse race between the two approaches? ;-) Or just iterate on #167?
