### ISSUE TITLE
rbd.Image.ReadAt and rbd.image.WriteAt are not thread-safe.

### ISSUE THREAD

**Issue by abligh** [ceph/go-ceph#18]
`rbd.Image.ReadAt()` and `rbd.image.WriteAt()` are not thread-safe (i.e. cannot safely be used from more than one go-routine) because they call `rbd.image.Seek()` without maintaing a mutex. The reason POSIX introduced (and golang simulates) `ReadAt` and `WriteAt` calls was specifically so that they can be used safely in a multithreaded environment.

I don't know whether `librbd` supports proper `ReadAt` and `WriteAt` calls. If it does then these should be used. If it does not then at the very least the documentation should carry a heavy warning that unlike `ReadAt()` and `WriteAt()` elsewhere in golang, these are not concurrency safe.

This is actually causing me a problem in gonbdserver, where I attempt to use a threaded backend to ensure that reads/writes to different OSDs execute in parallel. With the existing implementation, this is very unsafe.

**Comment by noahdesu** [comment]
Thanks for tackling this. I'll review this soon.

**Comment by noahdesu** [comment]
I just merged your patch, thanks. Looking through it you are correct. It's not clear why the ReadAt and WriteAt versions in there were modifying the offset state. I think this should be resolved now.

**Comment by abligh** [comment]
Thanks!
On 20 May 2016, at 15:35, Noah Watkins <notifications@github.com> wrote:

> I just merged your patch, thanks. Looking through it you are correct. It's not clear why the ReadAt and WriteAt versions in there were modifying the offset state. I think this should be resolved now.
> 
> �
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> 

-- 
Alex Bligh
