### ISSUE TITLE
Add support for ceph fs subvolume commands

### ISSUE THREAD

**Issue by Madhu-1** [ceph/go-ceph#202]
currently, cephcsi is directly calling the ceph fs subvolume commands, it would be nice if go-ceph provides an interface to call these commands.

Adding the link of subvolume commands https://docs.ceph.com/docs/master/cephfs/fs-volumes/

CC @ShyamsundarR @humblec @nixpanic

**Comment by phlogistonjohn** [comment]
Sounds reasonable. I expected we'd look into this eventually.
I believe that these are not specific function calls but rather use the mds/mon commands JSON api.
I've been tinkering with these on and off for a while. I'll reply later with a more comprehensive report.

**Comment by nixpanic** [comment]
Not a MDS/MON call, but some JSON to CephMgr. There is a `cephfs.MdsCommand()` already, we probably need to add `MgrCommand` in a non-cephfs specific location.

An other convenience layer can be added that hides the JSON request, and provides a simpler API.

**Comment by phlogistonjohn** [comment]
I just checked and it appears to be a mon command. You can see that the command is available in the "command description" JSON. By issuing `{"prefix": "get_command_descriptions"}` to the mon via MonCommand.

As a side task I've been playing around with these using [a little toy project](https://hg.sr.ht/~phlogistonjohn/faintglance) I recently started. If you're lazy like me you can use that to explore the commands the various ceph daemons support. In this case you can run `./faintglance mon fs subvolume` and see that it lists 'fs subvolume create' and 'fs subvolume rm' as available sub-commands.
This tool is far from mature but I have found it useful so far in my explorations and I plan to continue tinkering with it. Just now I used it to create the following using subvolumegroup create and subvolume create commands:
```
/tmp/ceph/mds/mnt/
`-- volumes
    |-- _nogroup
    |   |-- alice
    |   |   `-- 776d10ec-a47a-42e9-aec2-8fd92f876275
    |   |-- bob
    |   |   `-- 26dbf12a-0744-454c-b533-e456be521978
    |   `-- carl
    |       `-- 295384f6-dbb3-4f1c-8b6b-5fe75635f6ba
    `-- stuff
        `-- dave
            `-- 6037af67-1e5a-4d3d-b020-8634cb2acbf3
```

**Comment by phlogistonjohn** [comment]
That all said I do want to add an MdsCommand function, but I don't think not having it yet will block us from creating subvolumes.
