### ISSUE TITLE
Proposal: drop travis ci and use github ci

### ISSUE THREAD

**Issue by phlogistonjohn** [ceph/go-ceph#209]
Travis CI is pushing new projects to use a "beta" status of ".com" vs. ".org". On top of this I find their documentation somewhat poor and suffers from this confusing split of .com/.org. I propose we avoid these problems entirely and just switch to using the native github ci.

Looking for opinions. I have already prototyped some of the work required and it's not much. The only downside I see is that if a matrix job's params change, like when I recently added octopus, we'd have to remember to explicitly add that item to the branch protection rules (the checks are dis-aggregated).

I think this is worth it since we're not going to changing these frequently.

**Comment by nixpanic** [comment]
I agree that it is very annoying that the state of the CI builds is not always reported back. That is the only issue I have been seeing lately. Not sure if that problem lays with GitHub or Travis CI.

- What do you mean with `new projects to use a "beta" status of ".com" vs. ".org"`?
- Their documentation and other links on their sites cross domains a lot, .com, org and .community, I always assumed most of it counts for all their environments :man_shrugging: 
- https://www.traviscistatus.com/ shows an API outage on the .org domain for 27 March

Personally I do not care what CI we use. I have no experience with GitHub CI, so I can not say it works better or is more user-friendly.

For Ceph-CSI I am looking into ([WIP branch](https://github.com/nixpanic/ceph-csi/tree/ci/centos)) using a dedicated OpenShift hosted Jenkins environment in the CentOS CI. As Ceph-CSI uses go-ceph, we could run jobs there too.

**Comment by nixpanic** [comment]
Have you considered [CircleCI](https://github.com/marketplace/circleci)? I think Ceph-Nano uses that.

**Comment by phlogistonjohn** [comment]
> I agree that it is very annoying that the state of the CI builds is not always reported back. That is the only issue I have been seeing lately. Not sure if that problem lays with GitHub or Travis CI.
> 
>     * What do you mean with `new projects to use a "beta" status of ".com" vs. ".org"`?

Part of my frustration stems from this separation. To the best of my current understanding one can use public open source projects under "travis-ci.com"  if you enter a beta program. Traditionally, open source projects use "travis-ci.org". However, they appear to be encouraging new open source projects to use ".com". 

> 
>     * Their documentation and other links on their sites cross domains a lot, .com, org and .community, I always assumed most of it counts for all their environments man_shrugging
> 

On the surface that seems true and then as I tried to figure out what was going wrong this appears not be be true. At the very least ".com" reports back results to the PR using the newer github apis and the ".org" jobs dont. I find the docs in this area to be rather confusing.


>     * https://www.traviscistatus.com/ shows an API outage on the .org domain for 27 March
> 

I saw that when problems first started occuring. However its tagged as the issue applied to  ".com" whereas all the projects where I had issues were ".org". 

> 
> Personally I do not care what CI we use. I have no experience with GitHub CI, so I can not say it works better or is more user-friendly.
> 

It was easy to set up modulo an issue with the golang integration module. This is resolved by the v2-beta branch so that's what I'm using in my PR.


> For Ceph-CSI I am looking into ([WIP branch](https://github.com/nixpanic/ceph-csi/tree/ci/centos)) using a dedicated OpenShift hosted Jenkins environment in the CentOS CI. As Ceph-CSI uses go-ceph, we could run jobs there too.

Interesting.


> Have you considered [CircleCI](https://github.com/marketplace/circleci)? I think Ceph-Nano uses that.

No. I was aware of it as I did a very quick survey of ci when the idea first struck me. However, my goal wasn't to do a comprehensive evaluation of CI for the project but just to move to something that would work more consistently and the current team, myself in particular, could better control. It also turns out there are configuration for this repo that belong to one of the previous maintainers that I would also like to remove.

**Comment by phlogistonjohn** [comment]
I did this. I forgot to close this issue around the time of the release when I made the change.
