### ISSUE TITLE
Implement cephfs open file functions

### ISSUE THREAD

**Issue by phlogistonjohn** [ceph/go-ceph#217]
The cephfs is missing common file i/o related calls, including:
* open
* read
* write
* seek

The library should implement wrappers for the equivalent functions from libcephfs.

**Comment by fzc234** [comment]
Hi, @phlogistonjohn, I am currently working on project using go-ceph. I see that read dir is already supported, we can get inode and name of dir. Is it possible to add support to return the d_type of the dir in the dirEntry struct? In addition, current dir list function is unexported, will you change it to exported in your later release? Thank you very much.

**Comment by phlogistonjohn** [comment]
Yes, I certainly planned to implement a method to access the d_type information.

We changed the list function from an exported version to an unexported version during the development process because we were not sure if there would be a good use case for it. I'm glad to hear that there's interest in it. I will file issues for both these topics so we can track them independently of the file-open feature here. 
Thanks!

**Comment by fzc234** [comment]
Thank you @phlogistonjohn

**Comment by phlogistonjohn** [comment]
The enumerated functions are implemented and other issues have been filed to track items mentioned in the conversation here. Closing this issue. Any other related items can be taken up in new issues.
