### ISSUE TITLE
Implement cephfs link functions

### ISSUE THREAD

**Issue by phlogistonjohn** [ceph/go-ceph#218]
The cephfs wrapper library does not current wrap functions needed to manage links, such as:
* link
* unlink
* symlink
* readlink

These should be implemented.

**Comment by muditag85** [comment]
The 4 methods which need to be implemented are:
ceph_link()
ceph_unlink()
ceph_symlink
ceph_readlink()

Do we need to implement ceph_ll_ functions also for the above categories?

**Comment by nixpanic** [comment]
@phlogistonjohn has been working on the `cephfs/userperm.go` bits to prepare for the `*_ll_*` functions. As there are currently no `*_ll_*` functions implemented, I recommend sticj with the higher-level functions that you listed in the previous comment.

See PR #225 that adds a few other CephFS functions to get inspiration.

**Comment by agarwal-mudit** [comment]
Ok, thanks for the clarification. Have written the wrappers, writing UTs as of now. Will raise a PR once that is done.

**Comment by phlogistonjohn** [comment]
Please be aware that I've already started on 'unlink' and it can be seen in PR #225.

I do not recommend working on the "ll" functions at this time, unless you have a strong use case for them. I prefer getting the simpler APIs done first.

**Comment by agarwal-mudit** [comment]
Hi @phlogistonjohn 
I was trying to test the above functions and I think I need PR #225  for the same as I need to create files before I can create links. I can do some testing with directories but that would be very limited.

I will post the changes with limited testing and will update the same once PR #225 is in.
Same goes for unlink also, have implemented as of now but will remove before final checkin.

Please correct me if my understanding is wrong

**Comment by phlogistonjohn** [comment]
That all sounds fine, thanks.
