### ISSUE TITLE
Cannot build: could not determine kind of name for C.ceph_get_fs_cid

### ISSUE THREAD

**Issue by fzc234** [ceph/go-ceph#232]
Hi, I upgraded to v0.3.0, used to be v0.0.0. I tried to build my project, it had the problem:
# github.com/ceph/go-ceph/cephfs
../../../../go/pkg/mod/github.com/ceph/go-ceph@v0.3.0/cephfs/conn_nautilus.go:25:9: could not determine kind of name for C.ceph_get_fs_cid

Is there any clue how to solve it? THX

![image](https://user-images.githubusercontent.com/25211275/80464554-90617200-896c-11ea-9493-7e73ce25af2b.png)

**Comment by phlogistonjohn** [comment]
You're probablye building against a version of ceph older than nautilus. You can pass build tags that match the code name for the ceph version you're using. 
We have noted it here: https://github.com/ceph/go-ceph#installation
But in short you'll probably be wanting to pass either `-tags mimic` or `-tags luminous`.
Please let us know if that doesn't work for you.

**Comment by nixpanic** [comment]
In addition to the previous response, you can also run `make containerized-build` to build the `cephcsi` executable in a container where recent versions of development libraries and tools are available.

**Comment by fzc234** [comment]
It works by setting -tags mimic. Thank you guys. @phlogistonjohn @nixpanic
