### ISSUE TITLE
rbd: implement rbd_update_watch() to detect events on an image

### ISSUE THREAD

**Issue by nixpanic** [ceph/go-ceph#241]
librbd offers a way to get notified in case the metadata of an RBD image changes. [`rbd_update_watch()`](https://github.com/ceph/ceph/blob/master/src/include/rbd/librbd.h) can be used to setup a callback so that the application can get informed.

The `internal/callbacks` package should be useful for implementing this.

**Comment by phlogistonjohn** [comment]
Done in #320
