### ISSUE TITLE
Missing cephfs API components: function ceph_version

### ISSUE THREAD

**Issue by phlogistonjohn** [ceph/go-ceph#265]
The cephfs API implements function(s) below but go-ceph does not:
* ceph_version

This issue has been filed to track implementing this missing
functionality in the appropriate package within go-ceph.
Please refer to the Ceph C API for details about the function(s)
in question.

NOTE: This issue was generated by a script.
If the content is innacurate or wording seems a bit odd
please excuse the script and blame the creator @phlogistonjohn

**Comment by phlogistonjohn** [comment]
We don't have a bot/automation around non-maintainers getting assignee status. However, I'm happy to play bot today. :-)

**Comment by oct28-yjkim** [comment]
@phlogistonjohn I am not skilled in C related.
Is there anything worth noting?

**Comment by phlogistonjohn** [comment]
> @phlogistonjohn I am not skilled in C related.
> Is there anything worth noting?

I'd say this should be extremely similar to the version functions in rbd and rados: https://github.com/ceph/go-ceph/blob/1d2ef78c2fc0654028e6d6da822f1cbea8205cd7/rbd/rbd.go#L131  and https://github.com/ceph/go-ceph/blob/1d2ef78c2fc0654028e6d6da822f1cbea8205cd7/rados/rados.go#L57

You can use those as inspiration.

**Comment by ansiwen** [comment]
Resolved by #570
