### ISSUE TITLE
Missing rados API components: ioctx snapshots

### ISSUE THREAD

**Issue by phlogistonjohn** [ceph/go-ceph#269]
The rados API implements function(s) below but go-ceph does not:
* rados_ioctx_snap_create
* rados_ioctx_snap_get_name
* rados_ioctx_snap_get_stamp
* rados_ioctx_snap_list
* rados_ioctx_snap_lookup
* rados_ioctx_snap_remove
* rados_ioctx_snap_rollback
* rados_ioctx_snap_set_read

This issue has been filed to track implementing this missing
functionality in the appropriate package within go-ceph.
Please refer to the Ceph C API for details about the function(s)
in question.

NOTE: This issue was generated by a script.
If the content is innacurate or wording seems a bit odd
please excuse the script and blame the creator @phlogistonjohn

**Comment by agarwal-mudit** [comment]
Can pickup this if no one is working.

**Comment by agarwal-mudit** [comment]
Working on this issue and hitting a weird run time error while implementing rados_ioctx_snap_list()

This is the function definition: 

`int rados_ioctx_snap_list(rados_ioctx_t io, rados_snap_t *snaps, int maxlen) 
`

This is what I am passing as arguments and its compiling properly:

```
type SnapID C.rados_snap_t 
var snapList []snapID
snapList = make([]SnapID, cLen)                                                                                                                                                                                                                       
 ret := C.rados_ioctx_snap_list(ioctx.ioctx,  (*C.rados_snap_t)&snapList[0]), cLen)                     

```

The error I am getting is **rados: ret=4, Interrupted system call**

Unable to understand what I am doing wrong, or is this some Ceph issue only.

**Comment by phlogistonjohn** [comment]
You might want to double check that this is one of those calls that return positive numbers (of returned items for example) on success instead of 0. If you're using a getError wrapper you may need to use getErrorIfNegative instead.

**Comment by agarwal-mudit** [comment]
Oh yeah, I guess that's the reason I completely missed it. Let me try, thanks a lot @phlogistonjohn
