### ISSUE TITLE
Missing rbd API components: rbd namespaces

### ISSUE THREAD

**Issue by phlogistonjohn** [ceph/go-ceph#276]
The rbd API implements function(s) below but go-ceph does not:
* rbd_namespace_create
* rbd_namespace_exists
* rbd_namespace_list
* rbd_namespace_remove

This issue has been filed to track implementing this missing
functionality in the appropriate package within go-ceph.
Please refer to the Ceph C API for details about the function(s)
in question.

NOTE: This issue was generated by a script.
If the content is innacurate or wording seems a bit odd
please excuse the script and blame the creator @phlogistonjohn

**Comment by nixpanic** [comment]
@agarwal-mudit this one would be useful to have too :wink:

**Comment by agarwal-mudit** [comment]
Sure, will pick it up.

**Comment by agarwal-mudit** [comment]
While wrapping rbd_namespace_list(), I am getting following error:

err = -18 ==>  Invalid cross-device link

Its pretty weird because there is only one place in rbd_namespace_list() from where this error can be returned:

```
rbd_namespace_list() {
  .....
       std::vector<std::string> cpp_names;
       int r = librbd::api::Namespace<>::list(io_ctx, &cpp_names);
       if (r < 0) {
               return r;
        }
.....
}

```

**Comment by phlogistonjohn** [comment]
That seems pretty weird, at least the errno used. What's the call arguments in your code?

**Comment by agarwal-mudit** [comment]
Let me put the PR as a draft, anyway other three functions are ready.
