### ISSUE TITLE
Missing rbd API components: pool stats

### ISSUE THREAD

**Issue by phlogistonjohn** [ceph/go-ceph#278]
The rbd API implements function(s) below but go-ceph does not:
* rbd_pool_stats_create
* rbd_pool_stats_destroy
* rbd_pool_stats_get
* rbd_pool_stats_option_add_uint64

This issue has been filed to track implementing this missing
functionality in the appropriate package within go-ceph.
Please refer to the Ceph C API for details about the function(s)
in question.

NOTE: This issue was generated by a script.
If the content is innacurate or wording seems a bit odd
please excuse the script and blame the creator @phlogistonjohn

**Comment by agarwal-mudit** [comment]
Shall I pick up this?

**Comment by phlogistonjohn** [comment]
Sounds good, thanks!
