### ISSUE TITLE
Return rbd image ID from `Stat` function

### ISSUE THREAD

**Issue by Madhu-1** [ceph/go-ceph#293]
currently, it returns below info when Stat function is called 

https://github.com/ceph/go-ceph/blob/217e502afa108dd892a78fcdda3190aa7d8caa2c/rbd/rbd.go#L49-L57

it's missing the rbd image ID which is part of `rbd info` CLI command.
ID is required  for few operation ex: adding a task to remove an image from the trash  
cc @nixpanic

**Comment by nixpanic** [comment]
I had a look at this, and the ID is not part of the `librbd.rbd_image_info_t` struct, so we will not include it by default in the `rbd.ImageInfo` type either. There are a few struct that contain the ID of the image, but these are all returned when listing many images (not efficient).

However, the `rbd.Image` type has a method `GetId()` that returns `(string, error)`. So, you can efficiently get the ID of the image with `id, err := myImage.GetId()`.
