### ISSUE TITLE
Add support for V2 cloning

### ISSUE THREAD

**Issue by Madhu-1** [ceph/go-ceph#295]
The current clone functions don't provide an option to set cloning format v2, go-ceph needs to provide an option to support v2 cloning.

example rbd CLI command
`rbd clone test4@snap replicapool/test4clone --rbd-default-clone-format=2 --image-feature layering --pool=replicapool`

**Comment by nixpanic** [comment]
The ImageOption is indeed not defined within go-ceph. I'll add it for you.

In the mean while, until go-ceph has a release, you can define the option locally, and use is like this:
```go
package main

import (
	"github.com/ceph/go-ceph/rbd"
)

const (
	// go-ceph will provide rbd.ImageOptionCloneFormat
	imageOptionCloneFormat = rbd.ImageOption(12)
)

func main() {
	rio := rbd.NewRbdImageOptions()
	rio.SetUint64(imageOptionCloneFormat, 2)
}
```
The `rio` from the above code example can be passed as last argument to [`rbd.CloneImage()`](https://github.com/ceph/go-ceph/blob/master/rbd/rbd.go#L1196).

**Comment by phlogistonjohn** [comment]
FWIW the next regular planned release, which will be v0.4, is due next week. If there's anything else needed by csi that can be proposed for completion by then, now is a good time to flag that for priority.
