### ISSUE TITLE
Add support to list rbd snapshots of an image which are in trash

### ISSUE THREAD

**Issue by Madhu-1** [ceph/go-ceph#300]
Add support to list rbd snapshots of an image which are in the trash, the rbd CLI commands looks like `rbd snap ls <pool>/<image> --all`

@nixpanic can you add more context and other missing calls?

**Comment by nixpanic** [comment]
We seem to be missing some of the functions that are used in [`do_list_snaps()`](https://github.com/ceph/ceph/blob/master/src/tools/rbd/action/Snap.cc#L25) from the `rbd` command.

That function also lists `RBD_SNAP_NAMESPACE_TYPE_MIRROR`, which is not needed for this issue. Ceph Octopus introduced many RBD mirror functions, and implementing them would be a separate Issue/PR.

**Comment by agarwal-mudit** [comment]
As discussed with @dillaman in the last call we need to implement few functions to get this information:
1. snap_get_namespace_type()
2. snap_get_group_namespace()
3. snap_get_trash_namespace()
4. snap_get_mirror_namespace()

And some macros:
RBD_SNAP_NAMESPACE_TYPE_USER
RBD_SNAP_NAMESPACE_TYPE_GROUP 
RBD_SNAP_NAMESPACE_TYPE_TRASH 
RBD_SNAP_NAMESPACE_TYPE_MIRROR 

as mentioned by @nixpanic probably we don't need mirror functions can be handled in a separate PR.

PS: These functions are declared in librbd.hpp

cc @phlogistonjohn

**Comment by phlogistonjohn** [comment]
> As discussed with @dillaman in the last call we need to implement few functions to get this information:
> 
>     1. snap_get_namespace_type()
> 
>     2. snap_get_group_namespace()
> 
>     3. snap_get_trash_namespace()
> 
>     4. snap_get_mirror_namespace()
> 
> 
> And some macros:
> RBD_SNAP_NAMESPACE_TYPE_USER
> RBD_SNAP_NAMESPACE_TYPE_GROUP
> RBD_SNAP_NAMESPACE_TYPE_TRASH
> RBD_SNAP_NAMESPACE_TYPE_MIRROR
> 
> as mentioned by @nixpanic probably we don't need mirror functions can be handled in a separate PR.
> 
> PS: These functions are declared in librbd.hpp

We need to use the versions that are exported to C in librbd.h. These are already available as rbd_snap_get_namespace_type, rbd_snap_get_group_namespace, and so on. The enum values are defined in librbd.h.
The mirror related ones are new in octopus. I didn't check when the others got added. So nothing new needs to be done on the ceph side, which is good.

**Comment by agarwal-mudit** [comment]
Thanks @phlogistonjohn, will send a PR soon.
