### ISSUE TITLE
rbd stat not returning the parent image name

### ISSUE THREAD

**Issue by Madhu-1** [ceph/go-ceph#312]
Not able to get the parent image name from the image stat. executed below go program to get image stat

Tested with go-ceph 0.3
```go
package main

import (
	"fmt"

	"github.com/ceph/go-ceph/rados"
	"github.com/ceph/go-ceph/rbd"
)

const (
	poolname   = "replicapool"
)

func create_conn() (conn *rados.Conn, err error) {
	conn, err = rados.NewConn()
	if err != nil {
		return nil, fmt.Errorf("Error creating NewConn (%v)\n", err)
	}

	baseArgs := []string{
		"-m", "10.105.235.252:6789",
		"--id", "admin",
		"--key=" +"AQBAgOxexraiLxAAH3YLTTXjXLLaxLRGk6szMw==",
		"-c", "/etc/ceph/ceph.conf",
	}

	err = conn.ParseCmdLineArgs(baseArgs)
	if err != nil {
		return nil, fmt.Errorf("Error updating connection with args (%v) (%v)", baseArgs, err)
	}

	err = conn.Connect()
	if err != nil {
		return nil, fmt.Errorf("Error connecting to Ceph cluster (%v). Connection args (%+v)", err, baseArgs)
	}

	return
}

func main(){
	conn, err := create_conn()
	if err != nil {
		fmt.Printf("Error creating connection (%v)", err)
	}
	defer conn.Shutdown()

	ioctx, err := conn.OpenIOContext(poolname)
	if err != nil {
		fmt.Printf("Error creating IO context (%v)", err)
	}
	defer ioctx.Destroy()
	name:="csi-snap-0ac326e1-b212-11ea-b8ec-0242ac110010"
	image := rbd.GetImage(ioctx, name)
	if image == nil {
		fmt.Printf("Error getting image handle (%v)", err)
	}

	err = image.Open()
	if err != nil {
		fmt.Printf("Error opening image (%v)", err)
	}

	s, err := image.Stat()
	if err != nil {
		image.Close()
		fmt.Printf("Error fetching image info (%v)", err)
	}
	fmt.Printf("image stats for %s is %+v\n",name,s)
}
```

```bash
sh-4.4# ./main 
image stats for csi-snap-0ac326e1-b212-11ea-b8ec-0242ac110010 is &{Size:1073741824 Obj_size:4194304 Num_objs:256 Order:22 Block_name_prefix:rbd_data.1342dd18e86f Parent_pool:-1 Parent_name:}
```

Image info for same image from ceph cluster

```bash
sh-4.2# rbd info csi-snap-0ac326e1-b212-11ea-b8ec-0242ac110010 --pool=replicapool --format=json |python -mjson.tool
{
    "access_timestamp": "Fri Jun 19 09:48:35 2020",
    "block_name_prefix": "rbd_data.1342dd18e86f",
    "create_timestamp": "Fri Jun 19 09:48:35 2020",
    "features": [
        "layering",
        "deep-flatten",
        "operations"
    ],
    "flags": [],
    "format": 2,
    "id": "1342dd18e86f",
    "modify_timestamp": "Fri Jun 19 09:48:35 2020",
    "name": "csi-snap-0ac326e1-b212-11ea-b8ec-0242ac110010",
    "object_size": 4194304,
    "objects": 256,
    "op_features": [
        "clone-child"
    ],
    "order": 22,
    "parent": {
        "id": "1122bee6774f",
        "image": "csi-vol-82f6ec77-b20d-11ea-8d70-0242ac110010",
        "overlap": 1073741824,
        "pool": "replicapool",
        "pool_namespace": "",
        "snapshot": "42f2a80e-2c63-4498-9776-c5e7204d31ec",
        "trash": false
    },
    "size": 1073741824,
    "snapshot_count": 1
}
```

Expected Result:

The image stat should return the parent image name

**Comment by Madhu-1** [comment]
cc @nixpanic @phlogistonjohn

**Comment by agarwal-mudit** [comment]
Even parent pool name is -1, looks like these two fields are deprected.

These fields come from rbd_image_info_t and are deprected thus the function which fills these fields sets **nil** value, see [this](https://github.com/ceph/ceph/blob/c142003a02a57bf094b15762b4aadb66c0df5937/src/librbd/internal.cc#L189)

**Comment by Madhu-1** [comment]
But the fields are present in rbd CLI output. maybe its calling other functions to get these info's

**Comment by agarwal-mudit** [comment]
Yeah, fields are present but deprecated. Fields are not removed from the struct, but values are not being filled for those.
We need to find another way to get these values.

**Comment by Madhu-1** [comment]
> Yeah, fields are present but deprecated. Fields are not removed from the struct, but values are not being filled for those.
> We need to find another way to get these values.

okay, We need a Parent name to check the clone depth to flatten the image (which is required for snapshot feature in cephcsi). with the current implementation, I will go ahead with rbd CLI. once it's fixed in go-ceph will make use of go-ceph in cephcsi.

**Comment by agarwal-mudit** [comment]
I guess you can use GetParentInfo() to retrieve parent's information, [here](https://github.com/ceph/go-ceph/blob/3a0bacb0391ad1ff6d265da556b84ceb7ca4e78c/rbd/snapshot_nautilus.go#L26).

**Comment by nixpanic** [comment]
Full documentation (defaults to latest release) is at https://pkg.go.dev/github.com/ceph/go-ceph@v0.4.0/rbd?tab=doc

**Comment by agarwal-mudit** [comment]
@Madhu-1 Did you get a chance to try the above mentioned function?

**Comment by Madhu-1** [comment]
> @Madhu-1 Did you get a chance to try the above mentioned function?

Not yet, will look into it.

**Comment by Madhu-1** [comment]
Yeah it works i can take the parent details from the GetParentIfno()

**Comment by agarwal-mudit** [comment]
Ok, thanks for checking it quickly. We can close this issue.

**Comment by Madhu-1** [comment]
> Ok, thanks for checking it quickly. We can close this issue.

we can use this issue to remove the deprecated fields from go-ceph, it doesnt make sense to have ParentNae in stat output as it always returns empty

**Comment by phlogistonjohn** [comment]
We support ceph versions as far back as luminous. We should only remove these if they return nothing in luminous and all versions after.

**Comment by agarwal-mudit** [comment]
> We support ceph versions as far back as luminous. We should only remove these if they return nothing in luminous and all versions after.

Same behavior in luminious as well, [here](https://github.com/ceph/ceph/blob/420a6c7524ecee2b4c0d464e0b6f8bf02299ef59/src/librbd/internal.cc#L262).

**Comment by phlogistonjohn** [comment]
@agarwal-mudit do you want to make a PR for this?
