### ISSUE TITLE
provide support for errors.Is() and errors.As()

### ISSUE THREAD

**Issue by nixpanic** [ceph/go-ceph#316]
Golang 1.13 introduces support for comparing wrapped errors with the standard `"errors"` package. See the [1.13 release notes](https://tip.golang.org/doc/go1.13#error_wrapping) for details.

New versions of Golangci (v1.27, maybe earlier versions too?) complain about comparing `err == rbd.ErrNoIOContext`. Ceph-CSI is one such project where these new warnings can be observed. See ceph/ceph-csi#1184 for a description on how to run the golangci tests there.

It probably is sufficient when the go-ceph error types implement the `Is()` and `As()` methods (suggestion by @phlogistonjohn).

**Comment by phlogistonjohn** [comment]
Specifically, the errno based types should probably implement the Is() interface and do a comparison of the errno values.
Other sentinel errors, like those created from errors.New in the Go stdlib, should probably not need to be changed in go-ceph. They just need to be changed to use errors.Is() in whatever codebase(s) have decided to ban `err == ErrSentinel` (ceph-csi for example).

**Comment by nixpanic** [comment]
In case we want to return errors with more details, `fmt.Errorf("... %w ...", err)` can be used. That requires our go-ceph error types to implement `Unwrap()`.

**Comment by phlogistonjohn** [comment]
Using %w in Errorf is a feature of Go 1.13, which would restirct users of the lib to that version or higher. We can do the equivalent and provide Unwrap w/o using that formatter in Errorf and get the same feature set. %w automatically creates the wrapped errors but I don't think its strictly required for our use case.

**Comment by nixpanic** [comment]
I agree, in go-ceph there is no need to use `fmt.Errorf()`. But for projects that want to use it, our errors should implement `Unwrap()`, I think.

**Comment by ansiwen** [comment]
Ok, after reading up on this I realize, that sentinel or type-checked errors are not really deprecated. The reason to use `Is()` (sentinels) and `As()` (type-checked) is actually to make them still work with wrapped errors.

**Comment by phlogistonjohn** [comment]
> Ok, after reading up on this I realize, that sentinel or type-checked errors are not really deprecated. The reason to use `Is()` (sentinels) and `As()` (type-checked) is actually to make them still work with wrapped errors.

Agreed! Unfortunately, ceph-csi is trying to update one of the code-quality tools and it has an overzealous check that rejects these sorts of sentinel checks. Implementing the Is check sooner rather than later would allow ceph-csi to use errors.Is(...) to get around the silly rule this check tool is enforcing and future proof go-ceph a bit. :-)

**Comment by ansiwen** [comment]
Well, at least this rule check shows another mistake we did: we exposed the implementation of the error types, now we can't change it without without possibly breaking code. I'd love to make it impossible to use == on the error type.

**Comment by ansiwen** [comment]
Wait, we don't _have_ to implement an `Is()` method. You can use `errors.Is()` already now, which falls back to `==` if no `Is()` method is implemented.

**Comment by phlogistonjohn** [comment]
I don't think anything additional needs to be done here in light of PR #329 and #344. Therefore, I'm closing this issue. If we think this needs additional discussion we can reopen or file a new issue. Thanks!
