### ISSUE TITLE
A plan to deprecate and then drop support for Ceph 'luminous'

### ISSUE THREAD

**Issue by phlogistonjohn** [ceph/go-ceph#317]
As we continue to develop the library we sometimes have to make exceptions and build conditionals to work across multiple ceph versions. As of late I feel we've been putting in extra work to make the 'luminous' version of Ceph supported.

According to https://docs.ceph.com/docs/master/releases/general/ the expected lifetime of a release is 24 months:

> The lifetime of a stable release series is calculated to be approximately 24 months (i.e., two 12 month release cycles) after the month of the first release. For example, Mimic (13.2.z) will reach end of life (EOL) shortly after Octopus (15.2.0) is released. The lifetime of a release may vary because it depends on how quickly the stable releases are published.

The table header on that page currently indicates an expected EOL for luminous of 2019-06-01. However, at least one release of lumious *has* been done this year.

I'd like to suggest that we officially deprecate 'luminous' for go-ceph v0.5 (our next release, due Aug) and use the release to announce this deprecation. Upon the release of v0.6 (October 2020) we officially drop luminous support entirely.

To be clear: v0.5 and v0.6 will compile with luminous as long as the appropriate build tags are supplied, but for the following release luminous will no longer be expected to function. Consumers of go-ceph that are building on luminous will have two releases with the latest fixes and improvements before losing support. I think that is a sufficiently long enough warning period and time to change course if great demand for luminous is heard.

Thoughts?

**Comment by phlogistonjohn** [comment]
@nixpanic @ansiwen @agarwal-mudit Opinions?

**Comment by agarwal-mudit** [comment]
Sounds reasonable to me for 'luminious'. 
My suggestion would be to make this more systematic going forward where we sync with official ceph announements and give some estimates in advance like the 'ceph announcements'.

**Comment by nixpanic** [comment]
I am in favour of following the supported releases for the Ceph project. Once a version is not maintained anymore, there is no need for the next go-ceph version to function with the end-of-life release anymore.

So, dropping luminous and mimic in go-ceph v0.5 has my seal of approval :+1:

**Comment by Madhu-1** [comment]
Note: cephcsi supports Mimic+ https://github.com/ceph/ceph-csi#ceph-csi-features-and-available-versions.

**Comment by phlogistonjohn** [comment]
OK, I think there's fairly broad consensus to drop luminous. However, what to do with mimic is outstanding. I think we can comfortably support 3 versions especially as @Madhu-1 notes ceph csi still supports mimic.

**Comment by nixpanic** [comment]
Mimic has been retired as of today:
- https://lists.ceph.io/hyperkitty/list/dev@ceph.io/thread/X5IUICDEM4IVVWTMUTSSNEU424MB6WL7/
- https://ceph.io/releases/mimic-is-retired/

I do not think there is a need for the upcoming Ceph-CSI v3 to keep support for Mimic, it can probably deprecated there.

**Comment by nixpanic** [comment]
ceph/ceph-csi#1264 confirms that Ceph-CSI v3 will not require Ceph Mimic support anymore.

**Comment by phlogistonjohn** [comment]
Interesting, thanks for the heads up.

Here's my latest proposal:
* Deprecate both luminous and mimic for go-ceph v0.5.0
* Remove support for luminous in v0.6.0
* Remove support for mimic in v0.7.0

I think this gives any consumers of the library a very smooth transition path. One reason I am a little cautious about dropping stuff too quickly is that some users might be trying to use distro based packages for ceph and not always be able to use the latest.

If there are no objections to this plan as we approach the v0.5.0 release I'll lock this in in the release notes and probalby an update to the readme.

**Comment by nickjanus** [comment]
First of all, thanks for all your work on this project! I've got a patch that updates existing rados/ioctx calls to use newer librados calls support null chars in oids/omap keys. Since luminous' librados doesn't support these calls, the patch can only go into a release without luminous support. Would you consider supporting multiple releases in parallel for different ceph versions, or is that a shortcut to maintainer insanity?

Also, as a consumer of go-ceph, it seems like versions that support different major ceph releases should be separated by a major version. Incrementing a minor version and losing support for a cluster would be a nasty surprise.

**Comment by phlogistonjohn** [comment]
> First of all, thanks for all your work on this project! I've got a patch that updates existing rados/ioctx calls to use newer librados calls support null chars in oids/omap keys. Since luminous' librados doesn't support these calls, the patch can only go into a release without luminous support. Would you consider supporting multiple releases in parallel for different ceph versions, or is that a shortcut to maintainer insanity?
> 

Glad to hear from another user of the library!

Currently, we use build tags to separate functions/features that differ by major ceph version. Newer functions, say something only on nautilus and up may get tags like: "!luminous,!mimic". We also have some functions that are implemented differently but share a common function in go-ceph. An example of this are files "rbd/snapshot_mimic.go" and "rbd/snapshot_mimic.go". Both files implement GetParentInfo but the first uses rbd_get_parent_info and the second rbd_get_parent.

I generally suggest that if you have patches that you post them (when you're ready), and if you have questions about the general approach, API design, etc mark the pr as RFC and team can discuss it. If we decide that it would be better  to wait until luminous support is removed we can take that decision there and just wait on the PR until the time is right.


> Also, as a consumer of go-ceph, it seems like versions that support different major ceph releases should be separated by a major version. Incrementing a minor version and losing support for a cluster would be a nasty surprise.

We still are producing 0.y.z releases which means we don't promise backwards compatibility yet. So you can kind of imagine our 0.y releases as "major" until the lib is complete enough and stable enough to call 1.0. At that point we'll be following the typical Go approach to library stability.

I will note that that the cluster version and the client build version don't need to be the same. In fact, I was just working on the release notes for the upcoming release and wrote:
```
We plan to remove support for "luminous" in go-ceph
v0.6.0 and to remove support for "mimic" in go-ceph v0.7.0. If you are building
go-ceph against either of these versions of Ceph, please plan accordingly. Do
note that server-client version compatibility for go-ceph is the same as the
native Ceph libraries, as these are what go-ceph builds upon. These plans only
change what versions of Ceph go-ceph expects to successfully compile with.
```
(wording subject to change :-))

So I hope that alleviates some of the concern about the deprecation/removal plans.

**Comment by nickjanus** [comment]
Hi @phlogistonjohn, thanks for your reply! The release semantics make sense, I just wasn't familiar with what was being guaranteed for v0. 

Regarding ceph compatibility, the fork I'm using internally here is further behind than I thought! I was actually planning on adding build tags to one our consumers of go-ceph, but since that's already a convention upstream, updating our fork should make my life much easier. I'm going to work on our fork situation and getting my patch into a more upstream friendly format with build tags before submitting. Thanks again for your response and patience with a new user!

**Comment by phlogistonjohn** [comment]
Closing this. The plan is now made concrete in the v0.5.0 release notes. If we decide the plan needs adjusting, we'll do so in new issues, etc.
