### ISSUE TITLE
io.copy() got rbd: ret=22, Invalid argument

### ISSUE THREAD

**Issue by mysugar** [ceph/go-ceph#318]
```
	image,err := rbd.OpenImage(suite.storage.ioctx, "d1","")
	require.NoError(suite.T(), err)
	defer image.Close()
	lfile,err := os.Create("/tmp/d1.rbd")
	require.NoError(suite.T(), err)
	defer lfile.Close()
	wrriten,err := io.Copy(lfile,image)
	fmt.Println("Get File wrriten ",wrriten ," data to /tmp/d1.rbd")
	require.NoError(suite.T(), err)

```
Got
```
Get File wrriten  104857600  data to /tmp/d1.rbd
    TestCephRBDStorageSuite/TestGetFile: ceph_rbd_test.go:56: 
        	Error Trace:	ceph_rbd_test.go:56
        	Error:      	Received unexpected error:
        	            	rbd: ret=22, Invalid argument
        	Test:       	TestCephRBDStorageSuite/TestGetFile
    --- FAIL: TestCephRBDStorageSuite/TestGetFile (0.63s)
```
my rbd image size is 100M ,and afert this func /tmp/d1.rbd  size is also 100M.
any good idea?

**Comment by mysugar** [comment]
what about change
https://github.com/ceph/go-ceph/blob/d4440eb8c2966508ca4bf41240e6d3aefd144e97/rbd/rbd.go#L710-L712
to 
```
	if ret < 0 {
        size,_ := image.GetSize()
        if uint64(image.offset) == size {
			return 0, io.EOF
		}
		return 0, RBDError(ret)
	}
```

**Comment by nixpanic** [comment]
Reading from an RBD image that hits EOF, should return a short read, or `0` in case nothing is read. I do not understand why you would get `errno=22: Invalid argument`. Unless `io.Copy()` causes the offset for reading to pass EOF somehow. This needs a little more debugging to understand what is going on, and wht `rbd_read()` returns an error that we do not expect.

Please provide the following details:
- [ ] Ceph version of the client (local librdb.so)
- [ ] Ceph version of the cluster (remote OSDs)
- [ ] confirmation that your suggestion of the change prevents the problem
- [ ] PR with a new test case using `io.Copy()` (expected to fail CI)

Could you try the following? This could be a workaround:
```
image, err := rbd.OpenImage(suite.storage.ioctx, "d1","")
lr := io.LimitReader(image, image.GetSize())
writen, err := io.Copy(lfile,image)
```
That way, there is an additional LimitReader that prevents going passed `image.GetSize()`.

**Comment by mysugar** [comment]
Thanks for your workaround! That works!

1.Client version  12.2.13-0ubuntu0.18.04.2
2.Cluster version ceph version 12.2.13 (584a20eb0237c657dc0567da126be145106aa47e) luminous (stable)
3.My suggestion works (of course, i think  your solution is better)
4.Test case need further recurrence.

This problem seems related to the image.  `io.copy()` other images with no problem.

**Comment by phlogistonjohn** [comment]
I'm following up on a few issues. From my reading of this issue it sounds like the problem lies in the ceph libs rather than go-ceph. I also see that you are/were using ceph luminous client libs. If you could I'd like to suggest that you retest with newer ceph versions and if the issue does not reproduce we'll close this out.

I'll also point out that as of our v0.5.0 release, made earlier this week, we're officially deprecating luminous as a build target. In v0.6.0, due in October, building against luminous will be dropped.

**Comment by mysugar** [comment]
Thank you！The issue did not reproduce.
