### ISSUE TITLE
Omap operations on nonexistent object

### ISSUE THREAD

**Issue by immesys** [ceph/go-ceph#32]
I'm not super familiar with the C or C++ versions of librados, so this may be intended behavior but if you attempt to read omap values on a nonexistent object, you get an Input / Output error, not ErrorNotFound:

```golang
func TestOmapReturnedError(t *testing.T) {
	conn, _ := rados.NewConn()
	conn.ReadDefaultConfigFile()
	conn.Connect()
	ioctx, err := conn.OpenIOContext("mypool")
	if err != nil {
		panic(err)
	}
	_, err := ioctx.GetAllOmapValues("def.not.exist", "", "", 100)
	if err != rados.RadosErrorNotFound {
		t.Fatalf("unexpected error code %v", err)
	}
}
```

And I get: `unexpected error code rados: Input/output error`

I generally like to treat object not found errors differently from "can't speak to OSD or MON" errors, and Input/output error is a bit vague. If it is not possible to reliable disambiguate the errors and coerce the type with what librados gives us then feel free to close this, but it bugs me.

**Comment by Vicente-Cheng** [comment]
hi @immesys  ,

It return EIO (Input/output error) because you try to get non-exist omap.

The omap flag would be set when setup omap, so in this situation (never set omap and try to get it) return EIO I think it correct.

thanks!
vicente

**Comment by immesys** [comment]
Hi, to clarify, my perceived problem is:

If I try to get an omap value, and I receive I/O Error, I do not know if that means the object does not exist or if it means the network / cluster is degraded.

One possible solution I guess is for me to try stat the object after I get the I/O Error to see if the nonexistent object is the cause, but I find it odd that every other rados operation I do will return ErrorNotFound if you try interact with a nonexistent object but omap get will not.

I guess my question is, is there sufficient information at the librados level to disambiguate between sources of I/O error when you do this operation (not found vs other) without additional network round trips? If so, then I believe not using it is a bug. If not, then we can close this.

**Comment by Vicente-Cheng** [comment]
hi @immesys 

sorry for late reply : (

> If I try to get an omap value, and I receive I/O Error, I do not know if that means the object does not exist or if it means the network / cluster is degraded.

I think it means not exist here.

> One possible solution I guess is for me to try stat the object after I get the I/O Error to see if the nonexistent object is the cause, but I find it odd that every other rados operation I do will return ErrorNotFound if you try interact with a nonexistent object but omap get will not.

> I guess my question is, is there sufficient information at the librados level to disambiguate between sources of I/O error when you do this operation (not found vs other) without additional network round trips? If so, then I believe not using it is a bug. If not, then we can close this.

That because we need the omap flag to get it, or it would return nothing.
Then we try to decode it and you would get EIO return code.

for now, I think we do not have sufficient information to clarify these two situation, because the only way to setup omap flag is that you set omap (on my understanding)

The get omap op would return NotFound is that you have omap but you cloud not found omap iterator.
In above situation, you would get NotFound error.

thanks!!
vicente

**Comment by noahdesu** [comment]
Receiving EIO return value strikes me as a deeper issue. I can think of two reasons that might occur. The first is if there is a low-level problem in the rados cluster. If everything else is working fine, let's rule that out. The second option is that go-ceph is linking against a client C library that is incompatible with the cluster. I'm not sure to what extent all combinations of ceph versions are wire compatible. In any case, is that the only go-ceph test that is failing for you?

**Comment by immesys** [comment]
This is actually one of my own tests, and the object in question does not actually exist. My objection is, as you have observed, that I cannot distinguish between an unhealthy cluster, and a non-existent object. One is dire, the other inconsequential, so I would prefer if attempting to access a non-existent object returned ErrorNotFound rather than EIO which I typically treat as an indication of a more severe problem with the cluster.

**Comment by immesys** [comment]
If you are suggesting that it should not return EIO in this scenario then I will investigate librados version stuff, it is entirely possible that I am not linking against the same version the cluster is running. My build machine uses librados from the xenial repo whereas the cluster is running the latest jewel

**Comment by immesys** [comment]
Also, to explicitly answer your question, the cluster is healthy and everything else is working fine.

**Comment by noahdesu** [comment]
I'm suggesting that if the object is non-existent you should not be receiving EIO. It may be the case, but I am suspect because the error codes returned from librados are usually intuitive (e.g. I would expect something like ENONET). A quick test would be to execute the equivalent C code against your cluster and test the return value, as go-ceph is a very light wrapper around it. I have seen users have an issue where they have a version of ceph in /usr/ and /usr/local. What if you try to read a non-existent object with go-ceph? Certainly in that case we expect something like ENONET and EIO would be more evidence of something wrong with wrapper/library versions.

**Comment by immesys** [comment]
Ah, good, then we are on the same page.

Other operations appear to return rados.ErrorNotFound (like normal object reads as opposed to OMAP operations) when the object does not exist. I don't recall if I tested xattrs. 

I'll try redo this test with go-ceph linking against jewel librados either today or tomorrow and see if I get a change in error code.

**Comment by noahdesu** [comment]
I was able to get the travis-ci scripts running again today. I have them running for jewel and kraken, and all of the librados tests pass. Perhaps you could submit the test case that is failing for you so it can run on the CI infrastructure?

**Comment by immesys** [comment]
I believe that test will reproduce. I did the experiment linking against the latest librados.so and librados header files and I get the same results

**Comment by noahdesu** [comment]
Thanks for the patch, and it is indeed failing for both jewel and kraken. I'll take a look at this tomorrow I suspect it will be something simple.

**Comment by immesys** [comment]
Did this end up being something simple?

**Comment by noahdesu** [comment]
Sorry, got swamped. I just pushed a fix and merged your test case. It worked locally on my machine. Here is the CI job for the updated branch. If it passes then you should be good to go https://travis-ci.org/ceph/go-ceph/builds/193813916

**Comment by noahdesu** [comment]
The tests seemed to have passed. I'll close this. Please let me know if you have any other issues. Thanks again for reporting.

**Comment by immesys** [comment]
Awesome! Thank you!
