### ISSUE TITLE
Will a version based on octopus be released？

### ISSUE THREAD

**Issue by tanqiangyes** [ceph/go-ceph#321]
Will a version based on octopus be released? The following error always appears when I use v0.4. thanks.

`/root/go/pkg/mod/github.com/ceph/go-ceph@v0.4.0/rbd/features_nautilus.go:11:28: could not determine kind of name for C.RBD_FEATURE_MIGRATING`
`/root/go/pkg/mod/github.com/ceph/go-ceph@v0.4.0/rbd/features_nautilus.go:15:25: could not determine kind of name for C.RBD_FEATURE_NAME_MIGRATING
`

**Comment by nixpanic** [comment]
go-ceph already supports some features present in Octopus, it will be used by default. Are you looking for certain functionality that is missing?

What version of the Ceph libraries are installed in the environment where you build your go-ceph application? You can build against older versions of Ceph by passing `-tags mimic` and not have the features that Nautilus added. In the [README])https://github.com/ceph/go-ceph#installation) there are a few more details about working with different Ceph versions. Those errors suggest that you have libraries installed from before Nautilus. Updating your environment is recommended.

**Comment by tanqiangyes** [comment]
My ceph version is octopus. When I build my program, I execute ` go build -tags octopus`. However, the results are as you can see. So I tried the nautilus version, but something went wrong.

errors:
`/root/go/pkg/mod/github.com/ceph/go-ceph@v0.4.1-0.20200622132218-d4440eb8c296/rbd/features_nautilus.go:11:28: could not determine kind of name for C.RBD_FEATURE_MIGRATING`
`/root/go/pkg/mod/github.com/ceph/go-ceph@v0.4.1-0.20200622132218-d4440eb8c296/rbd/features_nautilus.go:15:25: could not determine kind of name for C.RBD_FEATURE_NAME_MIGRATING`

Below is a screenshot of my ceph version:
![image](https://user-images.githubusercontent.com/25723492/86331227-62095700-bc7b-11ea-86f8-632d01db266c.png)

I just want to test the Ceph. Below is my Code:
`package main

import (
	"fmt"
	"github.com/ceph/go-ceph/rados"
	"github.com/ceph/go-ceph/rbd"
)

func main() {
	conn, err := rados.NewConn()

	conn.ReadDefaultConfigFile()
	if err != nil {
		fmt.Println("error when read default config file:", err)
		return
	}

	err = conn.Connect()
	if err != nil {
		fmt.Println("error when connect:", err)
		return
	}

	fmt.Println("connect ceph cluster ok!")
	pools, _ := conn.ListPools()
	fmt.Println(pools)
	ctx, _ := conn.OpenIOContext("mytest")
	names, err := rbd.GetImageNames(ctx)
	fmt.Println(names, err)
	conn.Shutdown()
}`

Am I using it improperly? Please tell me! thanks!

**Comment by tanqiangyes** [comment]
sorry! I used mimic！Although I specified to download the octopus version, but still installed the mimic version for me! when i used `go build -tags mimic`, it`s ok! thanks!
