### ISSUE TITLE
make: make test-container is failing with latest code

### ISSUE THREAD

**Issue by agarwal-mudit** [ceph/go-ceph#325]
No new changes, just pulled the latest code and ran "make test-container CONTAINER_CMD=podman"

It failed with following error:

++ ceph-fuse /tmp/ceph/mds/mnt
terminate called after throwing an instance of 'std::system_error'
  what():  Invalid argument
/micro-osd.sh: line 93:   562 Aborted                 (core dumped) ceph-fuse ${MOUNTPT}
make: *** [Makefile:43: test-container] Error 134

**Comment by agarwal-mudit** [comment]
If I undo the latest [commit](https://github.com/ceph/go-ceph/commit/5ee762c586abea15791811df28988e0e066978ea), things work fine.

**Comment by nixpanic** [comment]
I just tried it out locally too, and hit the same problem.

After removing all relevant (my guess) images with `podman images` and `podman rmi ..`, running the tests worked again. (I might also have removed the `.build.nautilus` file.)

**Comment by agarwal-mudit** [comment]
I also deleted .build.nautilus yesterday but it didn't work, let me delete the relevant podman images and try again. Thanks.

**Comment by agarwal-mudit** [comment]
Yeah, it works. Thanks @nixpanic
