### ISSUE TITLE
Provide a way to administrate cephfs volumes

### ISSUE THREAD

**Issue by phlogistonjohn** [ceph/go-ceph#341]
The "ceph" command line tool provides various commands that an administrator can use to create/remove subvolumes, subvolumegroups, snapshots, etc. However, for cephfs, these functions are not part of the "libcephfs" API, which is mainly concerned with providing an API to access the file system contents.  These functions are available to code via APIs but are done by sending "JSON commands" to the MGR (or other services). Using JSON and the existing *Command functions in go-ceph can provide a convenient and less-costly [1]  way for programs in Go to manage cephfs.

I propose a new package "cephfs/admin" to encapsulate these functions and provide a clear and convenient way to call these functions.

[1] - Less costly than fork+exec to execute the "ceph" command line tool.

**Comment by phlogistonjohn** [comment]
This proposal is partly driven by ceph/ceph-csi/issues/1265  as well as general inclination not to have users of go-ceph need to research and implement the JSON structures needed for  serialization & de-serialization themselves.

**Comment by phlogistonjohn** [comment]
I forgot to mention: it should be a new package separate from "cephfs" as that package mirrors the functionality of "libcephfs". These new APIs would not be found in libcephfs and are creations of our own (based on what the JSON commands support) with function names and types that don't mirror anything in the ceph libs. To make that delineation clear, I think a new package is best.

**Comment by nixpanic** [comment]
Definitely a good thing to have. If it would not be part of go-ceph, Ceph-CSI and other projects needs to figure out the JSON structures that get sent to the Ceph Mgr for CeohFS administration.

**Comment by phlogistonjohn** [comment]
Reopening this to act as a tracker for other individual calls the package needs prior to the next release.

**Comment by phlogistonjohn** [comment]
done. 1st release is go-ceph v0.6.0.
