### ISSUE TITLE
Error handling - should .Errno() return negative errno values or absolute values?

### ISSUE THREAD

**Issue by phlogistonjohn** [ceph/go-ceph#343]
I'm raising this as a topic for discussion. This has bit me when working on my recent PR. I tried to use the new approach for error handling: using an interface check for an `Errno() int` method and then using that to get an errno and compare.
Unfortunately, I spent a long time scratching my head due to it not working as I expected. Ultimately, my problem was that the Errno() method returns the negative value (ex. -13) but the text of the error prints 'errno=13'.

My suggestion is to return an absolute value of the Errno, however I'm willing to hear other opinions. What do you folks think?

**Comment by phlogistonjohn** [comment]
@nixpanic @ansiwen @agarwal-mudit

**Comment by phlogistonjohn** [comment]
Of course, after I post this I realized that all of our constants are negative too. So I'm a bit less confident about my suggestion above, but I'd still like to discuss this.
Maybe we change how we print the errors?

**Comment by agarwal-mudit** [comment]
In our tests we are comparing with negative values so that the test cases pass.
I think we should keep it negative only, it feels more real and most of the users expect it in that way.
We can change how we print the errors if it doesn't break anything.

**Comment by nixpanic** [comment]
The definitions for the C `errno` are positive. In general, syscalls return -1, and set `errno` (see `man write` for an example). Libraries may work a little differently, and Ceph  seems to return negative values to indicate errors, where the negative value can be made absolute and matches an `errno` constant.

So, I'd like to have any `errno` reference use the positive value. Return values from functions may need to be made absolute.

If others prefer it the other way around, that's fine with me too, but we'll have to make our constants after `#include <errno.h>` negative (yuck).

**Comment by phlogistonjohn** [comment]
Internally, the constants are negative, like what ceph returns, for example:
```
»»»»// ErrNotFound indicates a missing resource.
»»»»ErrNotFound = radosError(-C.ENOENT)
»»»»// ErrPermissionDenied indicates a permissions issue.
»»»»ErrPermissionDenied = radosError(-C.EPERM)
»»»»// ErrObjectExists indicates that an exclusive object creation failed.
»»»»ErrObjectExists = radosError(-C.EEXIST)
```

But the users of the library should not be interacting directly with these values. IMO doing both `myerr == ErrPermissionDenied` and `myerr.Errno() == ErrPermissionDenied.Errno()` should work. The confusion comes from how the errors are represented in the libs and what the new Errno() function returns.

I don't see anywhere in the test code where we compare raw numbers for errnos. I did find that the LockShared/LockExclusive return both the returncode from ceph and an errno, which IMO is pretty strange and I had missed that up to this point.
So I don't really feel that being able to get the negative errno is what users of the library will expect.

I am back to feeling somewhat confident in my desire to change Errno() to return the absolute value of the error value as that result is an actual errno. Keep the internal values negative to match with ceph, and direct comparisons will continue to work.

**Comment by ansiwen** [comment]
The whole discussion is for me rather a sign to get rid of the Errno() method again :wink:, because I only added it for the potential corner cases, where someone used the int value already. But it should be an implementation detail I think. _If_ we offer Errno(), it certainly should return exactly the same value as the errno or ret value the error is derived from, as this is would follow the principle of least surprise. I wouldn't add something for "convenience" here. When I look at the code I think [this](https://github.com/ceph/go-ceph/commit/811f851c99d09ef8555da4b6fc2c55c61470f3be#diff-8283f12ebee977d84b183ebc18edb7f9) change was not so good, because it lies about the ret value. If strerror needs positive values I would only take the absolute value for that specific call, but keep the internal value verbatim. I wouldn't let strerror dictate our internal data. What if a ceph call decides to return positive _and_ negative values as errors? Let's keep it lean.

**Comment by nixpanic** [comment]
> Internally, the constants are negative, like what ceph returns, for example:

You show that `C.ENOENT` is a positive integer. I think that is how `<errno.h>` is intended to be used most of the time. There are exceptions, like the Ceph libraries returning a negative errno-matching-value is different from the `errno` variable that can be set when a function/syscall returns an error.

Most developers working with C and `<errno.h>` are probably more familiar with positive errno values (as `strerror()` suggests). So, I think we can go both ways here, and I don't object to either. I am not sure if `Errno()` needs to be exposed; we should recommend applications to match the errors returned with `errors.Is()`.

**Comment by phlogistonjohn** [comment]
After a voice discussion with most of the maintenance team we've decided to:
* Rename the function from Errno to ErrorCode to more closely reflect what wording the ceph API docs use and not imply the returned value must equal a unix style errno
* Change how the error messages are printed to include the minus sign if the error code value is actually negative. The helps the user (developer) who hits an error, wants to handle it and needs to match up the "inner" value with what was seen in a log, etc.

PR coming soon.
