### ISSUE TITLE
Add a new function similar to GetParentInfo() with retry logic 

### ISSUE THREAD

**Issue by agarwal-mudit** [ceph/go-ceph#347]
GetParentInfo() in rbd/snapshot_nautilus.go returns ERANGE in a weird manner and doesn't do a resize using the retry logic.
We should add a new function call that uses the nautilus+ apis.

More details: https://github.com/ceph/go-ceph/issues/185#issuecomment-673547374

**Comment by agarwal-mudit** [comment]
While implementing this, I realized that it actually doesn't need a retry logic or I am missing something. Please check #352

**Comment by phlogistonjohn** [comment]
> While implementing this, I realized that it actually doesn't need a retry logic or I am missing something. Please check #352

Agreed. The current api takes a buffer argument that may be too small for the name, and thus needs to retry. The rbd_get_parent call allocates new strings so it doesn't need to retry if the buffer(s) given are too small.
