### ISSUE TITLE
Missing rbd API components: snapshot

### ISSUE THREAD

**Issue by agarwal-mudit** [ceph/go-ceph#354]
Following functions are still missing for rbd snapshot:

int rbd_snap_get_timestamp(rbd_image_t image, uint64_t snap_id, struct timespec *timestamp);
int rbd_snap_set_by_id(rbd_image_t image, uint64_t snap_id);
int rbd_snap_get_name(rbd_image_t image, uint64_t snap_id, char *snapname, size_t *name_len);
int rbd_snap_get_id(rbd_image_t image, const char *snapname, uint64_t *snap_id);

There is no snapshot ID related API in go-ceph today (except GetSnapshotNames(), which resturns a list of snapshot)

**Comment by agarwal-mudit** [comment]
rbd_snap_get_timestamp() and rbd_snap_set_by_id() are there in ceph from **mimic** onwards

rbd_snap_get_name() and rbd_snap_get_id() are there only from **octopus**

**Comment by agarwal-mudit** [comment]
Both rbd_snap_get_timestamp() and rbd_snap_set_by_id() needs snap ID as an arugument, now user doesn't have a way to get snapID till octopus except 
1. he/she can call GetSnapshotNames(), 
2. matches snap name for the list of snapshot returned by GetSnapshotNames()
3. use the ID corresponding to the name in step 2

Either, [1] we can implement this logic inside the functions or [2] write a test case which some one can look on how to use these. 

Going with [2] as of now.

**Comment by agarwal-mudit** [comment]
rbd_snap_get_timestamp() is hitting a ceph assert for non-existing snap ID, have commented out the test case as of now. https://github.com/ceph/go-ceph/pull/365

Either we need to put this warning in comments or make sure that user doesn't pass invalid ID (that would be a lengthy process though given that we don't have a straight function to find snap ID)

**Comment by phlogistonjohn** [comment]
> rbd_snap_get_timestamp() is hitting a ceph assert for non-existing snap ID, have commented out the test case as of now. #365
> 

Understood. That is unfortunate.

> Either we need to put this warning in comments or make sure that user doesn't pass invalid ID (that would be a lengthy process though given that we don't have a straight function to find snap ID)

Documenting this is probably OK for now, given as you say there's no simple way to validate it ourselves. This does seem like a good candidate to file with ceph/ceph and have it return an errno like ENOENT or something.

**Comment by agarwal-mudit** [comment]
> Documenting this is probably OK for now, given as you say there's no simple way to validate it ourselves. This does seem like a good candidate to file with ceph/ceph and have it return an errno like ENOENT or something.

Have requested a ceph account, will raise an issue and add it in comments asap.
