### ISSUE TITLE
cephfs admin: how to get the metadata pool for a filesystem?

### ISSUE THREAD

**Issue by nixpanic** [ceph/go-ceph#375]
Hi!

With the new cephfs admin package I can use `VolumeStatus()` to get all the pools of a filesystem, and check for the `pool.Type == "metadata"` to identify the metadata pool. However, this functionality is only available for Ceph Octopus. Any suggestion how to get this information using Nautilus?

Thanks!

See-also: ceph/ceph-csi#1554

**Comment by phlogistonjohn** [comment]
Oh yeesh. Right now, I don't see an obvious way to do it outside of `fs ls` which is, of course, quite different from `fs volume ls`.
A couple of options:
* We try to get a backport from ceph to get `fs status` to return json when its requested
* We try to parse the textual output of `fs status` when that's what ceph returns
* We make use of `fs ls` to get this info (somewhat redundant with the other calls)

I checked `fs dump` and `fs get` and it only returns the pools but only the numeric pool ids, not the names!

I think the last item is the least friction but I find it somewhat disappointing to need it. To keep the apis smallish, I could re-write the ListVolumes terms of `fs ls` and then have a `ListVolumeDetails` that exposes *all* of the extra fields that `fs ls` has.

Thoughts?

**Comment by phlogistonjohn** [comment]
I decided not to try and abstract things too much and just added a ListFileSystems function. Please see linked PR.
