### ISSUE TITLE
provide an api to get mirroring status of rbd image

### ISSUE THREAD

**Issue by Madhu-1** [ceph/go-ceph#379]
From CLI

```
{
	"name": "pvcname-namespace-xxx-xxx-xxx",
	"id": "190d48946362",
	"size": 1073741824,
	"objects": 256,
	"order": 22,
	"object_size": 4194304,
	"snapshot_count": 2,
	"block_name_prefix": "rbd_data.190d48946362",
	"format": 2,
	"features": ["layering", "non-primary"],
	"op_features": [],
	"flags": [],
	"create_timestamp": "Thu Oct  8 14:19:35 2020",
	"access_timestamp": "Mon Oct 12 08:10:57 2020",
	"modify_timestamp": "Mon Oct 12 08:10:57 2020",
	"mirroring": {
		"mode": "snapshot",
		"state": "enabled",
		"global_id": "14e42673-a2ad-438a-aa5e-5b4fb59f1d8f",
		"primary": false
	}
}
```

current there is no function in go-ceph to get mirroring details for an image.

**Comment by Madhu-1** [comment]
cc @phlogistonjohn @nixpanic @agarwal-mudit

**Comment by agarwal-mudit** [comment]
@Madhu-1 This is which cli?

**Comment by Madhu-1** [comment]
sorry I forgot to provide CLI command :facepalm:  its `rbd info <image_name>`

**Comment by agarwal-mudit** [comment]
There is a Stat() function in librbd which prints the image information but looks like we need to enhance it (or add a new function) to print mirroring information too.

**Comment by agarwal-mudit** [comment]
The required information is part of rbd_mirror_image_info_t. 
Though the cli "rbd info <image name>" is displaying this but the corresponding API rbd_stat() doesn't care about it. 

We have two options, 
1) Enhance go-cpeh Stat() and make it return this info also or 
2) Implement rbd_mirror_image_get_info()

As an end user, I think people prefer to get all the information while call Stat() function because they are expecting it to be at par with "rbd info" command.

@phlogistonjohn

**Comment by ansiwen** [comment]
Well, but go-ceph not a CLI but an API, so shouldn’t we rather follow the
python API, which is probably the most „official“ API? What does python do
here?


Mudit Agarwal <notifications@github.com> schrieb am Di. 17. Nov. 2020 um
13:31:

**Comment by phlogistonjohn** [comment]
I'm a tad confused. If the api in ceph gets the mirroring information via a call (rbd_mirror_image_get_info I presume) but not from any other calls, I would say it should be a seperate call. However, your point 1 is worded in a way that I don't know if the current Stat call could be updated (via flags or whatnot) to also return data for mirroring.

So now I've briefly looked at both the C and python apis. It seems to be a separate call. As @ansiwen points out, the python call is mirror_image_get_info wrapping rbd_mirror_image_get_info. So taking our typical thin-but-not-too-thin layering approach I will strongly suggest a new function be added with a matching type to wrap rbd_mirror_image_info_t. This type can later be resued if we wrap rbd_mirror_image_info_list down the road.
