### ISSUE TITLE
Add support for RBD image-meta

### ISSUE THREAD

**Issue by diluga** [ceph/go-ceph#383]
hi，is any plan to add support for RBD image-meta？

image-meta get image-spec key
Get metadata value with the key.

image-meta list image-spec
Show metadata held on the image. The first column is the key and the second column is the value.

image-meta remove image-spec key
Remove metadata key with the value.

image-meta set image-spec key value
Set metadata key with the value. They will displayed in image-meta list.

**Comment by phlogistonjohn** [comment]
I think all the functions except list are already implemented.

The image methods GetMetadata, SetMetadata, and RemoveMetadata should be equivalent to the CLI commands you note above.
Only the C function rbd_metadata_list currently lacks an implementation. Would you mind if we narrow down this issue to a feature request for rbd_metadata_list?

**Comment by diluga** [comment]
> I think all the functions except list are already implemented.
> 
> The image methods GetMetadata, SetMetadata, and RemoveMetadata should be equivalent to the CLI commands you note above.
> Only the C function rbd_metadata_list currently lacks an implementation. Would you mind if we narrow down this issue to a feature request for rbd_metadata_list?

 rbd_metadata_list is not a strong dependency for me ，you can add it later。Thx!

**Comment by phlogistonjohn** [comment]
OK, in that case I will file a new issue to track that missing function and then I think we can close this one. If you have any objections please let me know. Otherwise, if I don't hear anything (or you agree) in a few days I'll close this.

**Comment by phlogistonjohn** [comment]
Closing this issue. See #384 to track the missing function from the set of all image metadata functions.
