### ISSUE TITLE
I got what(): buffer::end_of_buffer

### ISSUE THREAD

**Issue by hieutrtr** [ceph/go-ceph#39]
I'm using object storage with 3 OSD and 3 MON.
I implement client to create a IOContext for every pool to handle write and get. But seem it got this error in interval time of 2 to 4 minutes.

> terminate called after throwing an instance of 'ceph::buffer::end_of_buffer'

Anyone got the same error ?

**Comment by phlogistonjohn** [comment]
Hello, I'm automatically closing all issues filed prior to 2018 that have not been commented on recently. If this issue is still relevant to you please reopen the issue and restart the discussion. Thank you for your understanding.
