### ISSUE TITLE
Provide APIs for rbd mirroring functions

### ISSUE THREAD

**Issue by Madhu-1** [ceph/go-ceph#393]
Need an API to rbd mirroring for below functions

* rbd mirror image enable
```
rbd mirror image enable {pool-name}/{image-name} {mode}
```
* rbd mirror image disable
```
rbd mirror image disable {pool-name}/{image-name}
```
* rbd mirror image promote
```
rbd mirror image promote [--force] {pool-name}/{image-name}
```
* rbd mirror image demote
```
rbd mirror image demote {pool-name}/{image-name}
```
* rbd resync
```
rbd mirror image resync {pool-name}/{image-name}
```
* create mirror snapshot
```
rbd mirror image snapshot {pool-name}/{image-name}
```
* Add scheduling per image
```
rbd mirror snapshot schedule add [--pool {pool-name}] [--image {image-name}] {interval} [{start-time}]
```
* mirror image status
```
rbd mirror image status {pool-name}/{image-name}
```
* mirror pool status
```
rbd mirror pool status {pool-name}
```

detailed info at https://docs.ceph.com/docs/master/rbd/rbd-mirroring/

**Comment by phlogistonjohn** [comment]
These CLI calls appear to call C++ functions directly. However it does appear that librbd functions for at least some of these exist.

From the librbd.h in nautilus:
```
CEPH_RBD_API int rbd_mirror_image_enable(rbd_image_t image);
CEPH_RBD_API int rbd_mirror_image_disable(rbd_image_t image, bool force);
CEPH_RBD_API int rbd_mirror_image_promote(rbd_image_t image, bool force);
CEPH_RBD_API int rbd_mirror_image_demote(rbd_image_t image);
CEPH_RBD_API int rbd_mirror_image_resync(rbd_image_t image);
CEPH_RBD_API int rbd_mirror_image_get_info(rbd_image_t image,
                                           rbd_mirror_image_info_t *mirror_image_info,
                                           size_t info_size);
CEPH_RBD_API int rbd_mirror_image_get_status(rbd_image_t image,
                                             rbd_mirror_image_status_t *mirror_image_status,
                                             size_t status_size);
CEPH_RBD_API int rbd_mirror_image_get_instance_id(rbd_image_t image,
                                                  char *instance_id,
                                                  size_t *id_max_length);
```


I could not find "rbd mirror snapshot schedule add" is it in a released version of ceph?

**Comment by phlogistonjohn** [comment]
Never mind. It is in octopus (branch, don't know if its released yet. However it is not in the same file so I missed it first time around.

It appears to be mainly a wrapper around mgr_command with a prefix of : "rbd mirror snapshot schedule add" I didn't check the args for the json but it doesn't need new C functions to be wrapped. We will need to decide if the JSON construction and result handling should be done in go-ceph, similar to what we did for cephfs admin or if CSI wants ot take something like this as a one off wrt to JSON.

(I do want to do more generic command handling but I feel that's a discussion for another day.)

**Comment by phlogistonjohn** [comment]
Can we split this into multiple issues? Adding API wrappers for the rbd_mirror_image_* functions is dissimilar from doing JSON command arguments work.

**Comment by phlogistonjohn** [comment]
Let's use this to track only the missing functions in librbd listed above. I did also consider splitting the function list into groups, but that might hamper writing tests so I'm leaving them all together for now.

**Comment by phlogistonjohn** [comment]
It looks like there's a fair amount of change here between nautilus and octopus. @Madhu-1 does CSI expect to use these  features with ceph nautilus?

**Comment by phlogistonjohn** [comment]
I'll note that at least one of the command lines you mentioned in the original request doesn't exist on nautilus to the best of my knowledge.

**Comment by ansiwen** [comment]
> It appears to be mainly a wrapper around mgr_command with a prefix of : "rbd mirror snapshot schedule add" I didn't check the args for the json but it doesn't need new C functions to be wrapped. We will need to decide if the JSON construction and result handling should be done in go-ceph, similar to what we did for cephfs admin or if CSI wants ot take something like this as a one off wrt to JSON.

It seems like it might be a good option to split go-ceph into two parts: one is the Cgo interface to the C libraries, and one is more like a API client for the JSON RPC API and completely independent of Cgo. Does that make sense?

**Comment by phlogistonjohn** [comment]
> > It appears to be mainly a wrapper around mgr_command with a prefix of : "rbd mirror snapshot schedule add" I didn't check the args for the json but it doesn't need new C functions to be wrapped. We will need to decide if the JSON construction and result handling should be done in go-ceph, similar to what we did for cephfs admin or if CSI wants ot take something like this as a one off wrt to JSON.
> 
> It seems like it might be a good option to split go-ceph into two parts: one is the Cgo interface to the C libraries, and one is more like a API client for the JSON RPC API and completely independent of Cgo. Does that make sense?

Yeah, that's issue #396 - I figured it would be a split like we have in cephfs/admin. I was even thinking to call it 'rbd/admin' for symmetry. It's not fully independent of go-ceph/C apis, because the JSON is one aspect, but it still uses ceph specific (C) apis to send and receive the JSON messages to the mgr (or other services: mons, osds, etc).

**Comment by phlogistonjohn** [comment]
I think we have sufficient coverage to close this issue now. We have individual issues open for a few remaining gaps in the coverage. Any new APIs or ones we overlooked should be filed as new issues. Thanks!
