### ISSUE TITLE
Consider how to implement "rbd mirror snapshot schedule add" functionality

### ISSUE THREAD

**Issue by phlogistonjohn** [ceph/go-ceph#396]
In issue #393 certain equivalents for rbd command line tool functionality was requested. There I determined that while some of these command lines are backed by librbd functions, others are backed by sending "command json" through a mgr_command call.

Because mgr_command is already wrapped in go-ceph nothing needs to be done at the API wrapping level. However, we should what, if anything, should be done for higher level functionality. It might be helpful to find out how extensively ceph is going to make use of these interfaces now and in the near future.

**Comment by phlogistonjohn** [comment]
The following grep is aimed at getting a very rough sense of how much "json commands" are used in the `rbd` command line tool.

```
src/tools/rbd/action/Config.cc:  int r = rados.mon_command(cmd, in_bl, &out_bl, &ss);
src/tools/rbd/action/Config.cc:  r = rados.mon_command(cmd, in_bl, nullptr, &ss);
src/tools/rbd/action/Config.cc:  r = rados.mon_command(cmd, in_bl, nullptr, &ss);
src/tools/rbd/action/MirrorSnapshotSchedule.cc:  r = utils::mgr_command(rados, "rbd mirror snapshot schedule add", args,
src/tools/rbd/action/MirrorSnapshotSchedule.cc:  r = utils::mgr_command(rados, "rbd mirror snapshot schedule remove", args,
src/tools/rbd/action/MirrorSnapshotSchedule.cc:  r = utils::mgr_command(rados, "rbd mirror snapshot schedule list", args, &out,
src/tools/rbd/action/MirrorSnapshotSchedule.cc:  r = utils::mgr_command(rados, "rbd mirror snapshot schedule status", args,
src/tools/rbd/action/Perf.cc:  int r = rados.mgr_command(cmd, in_bl, &out_bl, &outs);
src/tools/rbd/action/TrashPurgeSchedule.cc:  r = utils::mgr_command(rados, "rbd trash purge schedule add", args,
src/tools/rbd/action/TrashPurgeSchedule.cc:  r = utils::mgr_command(rados, "rbd trash purge schedule remove", args,
src/tools/rbd/action/TrashPurgeSchedule.cc:  r = utils::mgr_command(rados, "rbd trash purge schedule list", args, &out,
src/tools/rbd/action/TrashPurgeSchedule.cc:  r = utils::mgr_command(rados, "rbd trash purge schedule status", args, &out,
```

Most of these calls seem to be about managing scheduled (for mirroring and for trash management).

@dillaman do you know, or can you point us at someone who knows, if there's any expectation that more rbd command line commands will be backed by this style of call, as opposed to C functions in librbd in the future? We're trying to decide if this needs a full-blown sub-package in go-ceph and if so how it should be constructed. Thanks in advance.

**Comment by dillaman** [comment]
Anything that is a background process run via the MGR will have a MGR json command. Anything that can be executed immediately on the librbd client side will have a librbd API.
