### ISSUE TITLE
Go CEPH operation RBD error

### ISSUE THREAD

**Issue by liweitaono1** [ceph/go-ceph#406]
# github.com/ceph/go-ceph/rbd
/root/go/src/github.com/ceph/go-ceph/rbd/options_octopus.go:11:31: could not determine kind of name for C.RBD_IMAGE_OPTION_MIRROR_IMAGE_MODE

**Comment by liweitaono1** [comment]
[root@ceph01 rbd]# ls
features.h  librbd.h  librbd.hpp
[root@ceph01 rbd]# pwd
/usr/include/rbd

**Comment by phlogistonjohn** [comment]
You're probably trying to use an older version of the ceph libs. go-ceph [uses build tags](https://github.com/ceph/go-ceph#installation) to help select what APIs we expect from ceph.  Please determine what version of ceph you are trying to compile with (nautilus, mimic, etc.) and pass the appropriate tag when compiling go-ceph.

**Comment by liweitaono1** [comment]
After the compilation passes, the runtime is blocked here

imageNames, err := rbd.GetImageNames(ioctx)

**Comment by liweitaono1** [comment]
func GetImageNames(ioctx *rados.IOContext) ([]string, error) {
     ...... 
	retry.WithSizes(32, 4096, func(s int) retry.Hint {
		size = C.size_t(s)
		images = make([]C.rbd_image_spec_t, size)
		ret := C.rbd_list2(
			cephIoctx(ioctx),
			(*C.rbd_image_spec_t)(unsafe.Pointer(&images[0])),
			&size)
		err = getErrorIfNegative(ret)
		return retry.Size(int(size)).If(err == errRange)
	})
   ......
}

In this function, C.rbd_list2 did not return. Is there a problem with the Lib library or something

**Comment by phlogistonjohn** [comment]
There are a couple things you can try. But without more information it's hard for us to say why this might be happening to you.

You can try to increase the logging you get from ceph libs when you run the client. For go-ceph, you can refer to a [blog post I wrote](http://asynchrono.us/how-i-work-on-go-ceph.html) in the latter half. For ceph config itself refer to [the troubleshooting docs](https://docs.ceph.com/en/latest/rados/troubleshooting/log-and-debug/#subsystem-log-and-debug-settings).

If you think go ceph is doing something wrong you can try either running the code under a debugger, such as delve, to confirm that is indeed where things are going wrong for yoy. Sometimes I write a tiny C program using the native ceph C apis to check behaviors w/o the go layer in between.

Hope some of this was useful. If you find out more about what's happening for your situation feel free to add it here and we'll try to provide additional assistance.

**Comment by liweitaono1** [comment]
I'm sure that in the C library call,  There was an error in c.rbd_List2, either using delve or printing debugging information. Hangs was there. And nothing was found in CEPH log
I previously printed the debug information in go CEPH

func GetImageNames(ioctx *rados.IOContext) ([]string, error) {
        var (
                err    error
                images []C.rbd_image_spec_t
                size   C.size_t
        )
        retry.WithSizes(32, 4096, func(s int) retry.Hint {
                size = C.size_t(s)
                images = make([]C.rbd_image_spec_t, size)
                fmt.Println(4)
                ret := C.rbd_list2(
                        cephIoctx(ioctx),
                        (*C.rbd_image_spec_t)(unsafe.Pointer(&images[0])),
                        &size)
                fmt.Println(5)
                err = getErrorIfNegative(ret)
                return retry.Size(int(size)).If(err == errRange)
        })
        fmt.Println(6)
        if err != nil {
                return nil, err
        }
        defer C.rbd_image_spec_list_cleanup((*C.rbd_image_spec_t)(unsafe.Pointer(&images[0])), size)

        names := make([]string, size)
        for i, image := range images[:size] {
                names[i] = C.GoString(image.name)
        }
        return names, nil
}


only display 4

**Comment by liweitaono1** [comment]
I'm sure that in the C library call, There was an error in c.rbd_List2, either using delve or printing debugging information. Hangs was there. And nothing was found in CEPH log
I previously printed the debug information in go CEPH

func GetImageNames(ioctx *rados.IOContext) ([]string, error) {
    var (
            err error
            images []C.rbd_image_spec_t
            size C.size_t
    )
    retry.WithSizes(32, 4096, func(s int) retry.Hint {
        size = C.size_t(s)
        images = make([]C.rbd_image_spec_t, size)
        fmt.Println(4)
        ret := C.rbd_list2(
                cephIoctx(ioctx),
                (*C.rbd_image_spec_t)(unsafe.Pointer(&images[0])),
                &size)
        fmt.Println(5)
        err = getErrorIfNegative(ret)
        return retry.Size(int(size)).If(err == errRange)
    })
    fmt.Println(6)
    if err != nil {
        return nil, err
    }
    defer C.rbd_image_spec_list_cleanup((*C.rbd_image_spec_t)(unsafe.Pointer(&images[0])), size)

    names := make([]string, size)
    for i, image := range images[:size] {
            names[i] = C.GoString(image.name)
    }
    return names, nil
}

only display 4

**Comment by liweitaono1** [comment]
I'm sure that in the C library call, There was an error in c.rbd_List2, either using delve or printing debugging information. Hangs was there. And nothing was found in CEPH log
I previously printed the debug information in go CEPH

```
func GetImageNames(ioctx *rados.IOContext) ([]string, error) {
        var (
                err    error
                images []C.rbd_image_spec_t
                size   C.size_t
        )
        retry.WithSizes(32, 4096, func(s int) retry.Hint {
                size = C.size_t(s)
                images = make([]C.rbd_image_spec_t, size)
                fmt.Println(4)
                ret := C.rbd_list2(
                        cephIoctx(ioctx),
                        (*C.rbd_image_spec_t)(unsafe.Pointer(&images[0])),
                        &size)
                fmt.Println(5)
                err = getErrorIfNegative(ret)
                return retry.Size(int(size)).If(err == errRange)
        })
        fmt.Println(6)
        if err != nil {
                return nil, err
        }
        defer C.rbd_image_spec_list_cleanup((*C.rbd_image_spec_t)(unsafe.Pointer(&images[0])), size)

        names := make([]string, size)
        for i, image := range images[:size] {
                names[i] = C.GoString(image.name)
        }
        return names, nil
}
```

only display 4

**Comment by liweitaono1** [comment]
And I tried other methods, all hang in the C library call

```package main

import (
	"fmt"
	"github.com/ceph/go-ceph/rados"
	"github.com/ceph/go-ceph/rbd"
)

func NewConn() (*rados.Conn, error) {
	conn, err := rados.NewConn()
	if err != nil {
		return nil, err
	}

	err = conn.ReadDefaultConfigFile()
	if err != nil {
		return nil, err
	}

	err = conn.Connect()
	if err != nil {
		return nil, err
	}

	return conn, nil
}
func ListImages(ioctx *rados.IOContext) {
	tmp,err:=rbd.GetTrashList(ioctx)
	if err != nil{
		fmt.Println(err)
	}
	fmt.Println(123)
	fmt.Println(tmp)
	//imageNames, err := rbd.GetImageNames(ioctx)
	//if err != nil {
	//	fmt.Println("error when getImagesNames", err)
	//}
	//fmt.Println(imageNames)
}

func ListPools(conn *rados.Conn) ([]string, error) {
	pools, err := conn.ListPools()
	defer conn.Shutdown()
	if err != nil {
		return nil, err
	}
	return pools, nil
}

func DeletePool(conn *rados.Conn, pool string) error {
	err := conn.DeletePool(pool)
	defer conn.Shutdown()
	if err != nil {
		return err
	} else {
		return nil
	}
}

func MakePool(conn *rados.Conn, pool string) error {
	err := conn.MakePool(pool)
	defer conn.Shutdown()
	if err != nil {
		return err
	} else {
		return nil
	}
}

func ClusterStats(conn *rados.Conn) (all, avail, used uint64, err error) {
	res, err := conn.GetClusterStats()
	defer conn.Shutdown()
	if err != nil {
		return 0, 0, 0, nil
	} else {
		return res.Kb, res.Kb_avail, res.Kb_used, nil
	}
}
func main() {
	conn, err := NewConn()
	ioctx, err := conn.OpenIOContext("test")
	if err != nil {
		fmt.Println("error when openIOContext", err)
	}
	defer ioctx.Destroy()

	ListImages(ioctx)

	//name := "go-ceph-image"
	//img, err := rbd.Create(ioctx, name, 1<<20, 20)
	//if err != nil {
	//	fmt.Println("error when create rbd image", err)
	//	return
	//}
	//listImages(ioctx)
	//
	//err = img.Remove()
	//if err != nil {
	//	fmt.Println("error when remove image", err)
	//	return
	//}
	//listImages(ioctx)
}
```

**Comment by liweitaono1** [comment]
I found the problem. The number of copies per node is not enough, which leads to the block storage problem, but it does not return. I don't think it is reasonable
