### ISSUE TITLE
cephfs test TestFilePreadvPwritev fails when run with cgocheck=2

### ISSUE THREAD

**Issue by phlogistonjohn** [ceph/go-ceph#412]
The test panics with: "fatal error: Go pointer stored into non-Go memory"

The library code should be updates so that it no longer violates these pointer rules and the test passes when run with cgocheck=2.

**Comment by ansiwen** [comment]
TestIovec/setBufs also fails, which is the underlying issue.

**Comment by phlogistonjohn** [comment]
This has been resolved in PRs #411 and #441.
