### ISSUE TITLE
rados tests TestReadWriteOmap & TestReadFilterOmap

### ISSUE THREAD

**Issue by phlogistonjohn** [ceph/go-ceph#413]
The test panics with: "fatal error: Go pointer stored into non-Go memory"

The library code should be updates so that it no longer violates these pointer rules and the test passes when run with cgocheck=2.

This is treated as one issue because these two tests ultimately test the same cgo code in the library.

**Comment by ansiwen** [comment]
This is fixed by #408. Closing.
