### ISSUE TITLE
rbd image writeAt stuck on rbd_write

### ISSUE THREAD

**Issue by clwluvw** [ceph/go-ceph#424]
I'm doing a write to an rbd image in a 5-second interval and after a while for example 30 seconds it will be stuck on `rbd_write`. I'm writing a 4096  bytes array with all 1 to an offset 0.
cluster health is OK and using octopus 15.2.8 on both client and cluster side.

**Comment by clwluvw** [comment]
I've also checked the connections to my cluster with `netstat` from the client and there was no established connection to the cluster when it gets stuck! It seems there is an internal go-ceph bug!

**Comment by clwluvw** [comment]
I've tested the same behavior with `librbdpy` and everything works great!

**Comment by phlogistonjohn** [comment]
Could you please post some example code so we can understand the exact issue better? Ideally, we'd like to see the failing go code and the working python so we can compare.
Thanks!

**Comment by clwluvw** [comment]
## go-ceph
```go
conn, _ := rados.NewConnWithUser(conf.RBDUser)
conn.SetConfigOption("rbd_cache", "false")
monitors := strings.Join(conf.Monitors, ",")
args := []string{"-m", monitors, "--keyring", conf.RBDKeyringPath}
conn.ParseCmdLineArgs(args)
conn.Connect()

ioctx, _ := conn.OpenIOContext(fs.config.PoolName)
fs.imgCtx, _ = rbd.OpenImage(ioctx, fs.config.ImgName, rbd.NoSnapshot)

for {
	<-ticker.C
	n, err := fs.imgCtx.Discard(0, uint64(fs.config.Req.FileSize))
	if err != nil {
                panic(err)
	}

	data := createAllOneBytesArray(req.FileSize)
	n, err = fs.imgCtx.WriteAt(data, 0)
	if err != nil {
                panic(err)
	}
}
```

## librbdpy
```python
cluster = rados.Rados(rados_id=self.rbd_user, conf={
    "mon_host": ",".join(self.monitors),
    "keyring": self.rbd_keyring_path,
    "rbd_cache": "false",
})
cluster.connect()
ioctx = rados_connection.open_ioctx(self.pool_name)
self.image_ioctx = rbd.Image(ioctx, self.image_name)

while True:
    time.sleep(self.interval)
    self.image_ioctx.discard(0, self.object_size)

    data = b'1' * self.object_size
    self.image_ioctx.write(data, 0)
```

**Comment by phlogistonjohn** [comment]
Thanks! Here are some quick thoughts w/o being able to try any of it out myself today:

go-ceph implements WriteAt using rbd_write. the python library wraps rbd_write2. This is a difference, but when I look at the implementation of these they differ only in the the former invokes the lower level C++ with a flags value of 0. I would be quite surprised to see that make a major difference.


I'm not 100% sure if the config parameters make a difference but one thing possibly worth trying would be to move your conn.SetConfigOption line below the ParseCmdLineArgs line, just in case it makes a difference. If it does please say so and we'll add documentation.

Last quick thought for now: is there an object_size value small enough that this starts to work, or does it behave the same for all object sizes? I'm guessing its fairly large, but knowing where it makes a difference to the overall behavior may be helpful.

**Comment by clwluvw** [comment]
> go-ceph implements WriteAt using rbd_write. the python library wraps rbd_write2. This is a difference, but when I look at the implementation of these they differ only in the the former invokes the lower level C++ with a flags value of 0. I would be quite surprised to see that make a major difference.

Yes I saw that and I've tested with `rbd_write2` in `go-ceph` (vendor my modules and build from the vendor) and nothing changes.

> I'm not 100% sure if the config parameters make a difference but one thing possibly worth trying would be to move your conn.SetConfigOption line below the ParseCmdLineArgs line, just in case it makes a difference. If it does please say so and we'll add documentation.

How it can help?! It will do an IO for 30 seconds for example after that it will be stuck and I don't think the order of configs can help here. Also, configs are applied before rados connect! It's a bit strange :thinking: 

> Last quick thought for now: is there an object_size value small enough that this starts to work, or does it behave the same for all object sizes? I'm guessing its fairly large, but knowing where it makes a difference to the overall behavior may be helpful.

The object size is the same for both `librbdpy` and `go-ceph` and also it's 4096 bytes. I've also tested with 500 and it gets stuck again! The other worth thing here is if I set the size to 4MiB `go-ceph` won't do IO at any time and will get stuck again but `librbdpy` will do!

**Comment by clwluvw** [comment]
> go-ceph implements WriteAt using rbd_write. the python library wraps rbd_write2. This is a difference, but when I look at the implementation of these they differ only in the the former invokes the lower level C++ with a flags value of 0. I would be quite surprised to see that make a major difference.

Yes I saw that and I've tested with `rbd_write2` in `go-ceph` (vendor my modules and build from the vendor) and nothing changes.

> I'm not 100% sure if the config parameters make a difference but one thing possibly worth trying would be to move your conn.SetConfigOption line below the ParseCmdLineArgs line, just in case it makes a difference. If it does please say so and we'll add documentation.

How it can help?! It will do an IO for 30 seconds for example after that it will be stuck and I don't think the order of configs can help here. Also, configs are applied before rados connect! It's a bit strange :thinking: 
I have also tested `go-ceph` without the `SetConfigOption` and nothing changes!

> Last quick thought for now: is there an object_size value small enough that this starts to work, or does it behave the same for all object sizes? I'm guessing its fairly large, but knowing where it makes a difference to the overall behavior may be helpful.

The object size is the same for both `librbdpy` and `go-ceph` and also it's 4096 bytes. I've also tested with 500 and it gets stuck again! The other worth thing here is if I set the size to 4MiB `go-ceph` won't do IO at any time and will get stuck again but `librbdpy` will do!

**Comment by phlogistonjohn** [comment]
I've tried to reproduce the reported issue in our test suite, but am unable to see the issue you see:
https://github.com/phlogistonjohn/go-ceph/blob/16d3f0966da60744f6aedcde22fdbea1b5ddf1b0/rbd/rbd_test.go#L1626

I've tried various sizes and the result is the same for me: the loop exits successfully.

To continue debugging I suggest trying to remove any extra confounding factors in your setup and test code to find a minimal reproducer. Eliminate any differences in the environment between the python version and the Go version if you haven't already, make sure they're both using the same underlying .so  files, same client config, same client, etc.

You may also want to enable debugging in the ceph conf file (see [my blog post](http://asynchrono.us/how-i-work-on-go-ceph.html) on how I do this with go-ceph if you need pointers). This will cause ceph libs to print out some information about what it is doing. I have used this with some success a few time. You will probably need to tinker with which [subsystems to log](https://docs.ceph.com/en/latest/rados/troubleshooting/log-and-debug/#subsystem-log-and-debug-settings).

Until you have a better idea about what is causing the problem for you there's not much we can do. The code in go-ceph that implements the I/O calls is fairly straightforward and I don't see anything obvious to investigate, esp. when I compare it to the python implementation.
