### ISSUE TITLE
Add support for rbd/rados async read&write

### ISSUE THREAD

**Issue by diluga** [ceph/go-ceph#43]
i that any plan to add support for rbd/rados async read&write?

**Comment by dswarbrick** [comment]
You might want to check out https://github.com/hangzws/go-ceph/pull/2.

**Comment by phlogistonjohn** [comment]
Hello, I'm automatically closing all issues filed prior to 2018 that have not been commented on recently. If this issue is still relevant to you please reopen the issue and restart the discussion. Thank you for your understanding.
