### ISSUE TITLE
Add support for cephfs mirroring APIs

### ISSUE THREAD

**Issue by Madhu-1** [ceph/go-ceph#444]
With the Ceph Pacific release, CephFS will support asynchronous replication of snapshots to a remote CephFS file system 

For more details about the feature: https://docs.ceph.com/en/latest/dev/cephfs-mirroring

**Note:-** Currently the ceph tool does not expose direct API to mirroring the subvolumes or subvolumegroups. Need to check with the cephfs team is there any plan to provide the Subvolume interface to do the same and also in which release it's going to be available.

**Comment by phlogistonjohn** [comment]
This appears to be available in pacific -  https://docs.ceph.com/en/pacific/dev/cephfs-mirroring/ -  we should start working on getting some of this in for the v0.11 release.  AFAICT most of the work ought to occur in the cephfs admin package.
