### ISSUE TITLE
cephfs: SubVolumeInfo structure doesn't have "state" attribute for the subvolume

### ISSUE THREAD

**Issue by agarwal-mudit** [ceph/go-ceph#453]
****SubVolumeInfo** structure doesn't have "**state**" attribute for the subvolume****

If you run "ceph fs subvolume info" command it displays attributes for a subvolume, for example:  

sh-4.2# ceph fs subvolume info myfs m1
{
    "atime": "2021-01-29 12:29:28", 
    "bytes_pcent": "undefined", 
    "bytes_quota": "infinite", 
    "bytes_used": 0, 
    "created_at": "2021-01-29 12:29:28", 
    "ctime": "2021-01-29 12:29:28", 
    "data_pool": "myfs-data0", 
    "features": [
        "snapshot-clone", 
        "snapshot-autoprotect", 
        "snapshot-retention"
    ], 
    "gid": 0, 
    "mode": 16877, 
    "mon_addrs": [
        "10.101.86.141:6789"
    ], 
    "mtime": "2021-01-29 12:29:28", 
    "path": "/volumes/_nogroup/m1/972f9188-23be-46fc-a2c1-1355f2e566f0", 
    "pool_namespace": "", 
    "state": "complete", 
    "type": "subvolume", 
    "uid": 0
}

This includes "state" attribute also but SubVolumeInfo structure in go-ceph lacks that attribute.

Looks like this attribute was newly added via backport, it is not a must but good to have.

**Comment by agarwal-mudit** [comment]
@phlogistonjohn I am adding state field in the SubVolumeInfo structure. We should handle the case where the state field is not present in the json. But I think if the field is not present in the json it won't affect us as of today because we no where check whether all the fields are returned or not. 
For example if a subvolume is in snapshot-retained state we will only get 4 attributes:
{
    "features": [
        "snapshot-clone", 
        "snapshot-autoprotect", 
        "snapshot-retention"
    ], 
    "mon_addrs": [
        "10.101.86.141:6789"
    ], 
    "state": "snapshot-retained", 
    "type": "subvolume"
}
And for such cases, we don't care for other fields in go-ceph. As of today, user of go-ceph (lets say ceph csi) has to take care of this. Same should happen in case of "state" field. 

That is why I have raised #454, if we are going to fix that then we might have to take care of this.

**Comment by phlogistonjohn** [comment]
That's fine. We should just ensure that we have a sensible zero value for the field and that both the present and missing cases get tested.
