### ISSUE TITLE
cephfs: Deleted subvolume (with retained snapshots) doesn't display all the attributes.

### ISSUE THREAD

**Issue by agarwal-mudit** [ceph/go-ceph#454]
This is actually a Ceph feature that when you delete a subvolume with --retain-snapshots command and then run the subvolume info" on the same volume it will return only very limited attributes. 

Example:
sh-4.2# ceph fs subvolume info myfs csi-vol-6ed1eaac-622c-11eb-8f93-0242ac110010 csi                   
{
    "features": [
        "snapshot-clone", 
        "snapshot-autoprotect", 
        "snapshot-retention"
    ], 
    "mon_addrs": [
        "10.101.86.141:6789"
    ], 
    "state": "snapshot-retained", 
    "type": "subvolume"
}

Now, this is a problem because go-ceph  doesn't care whether all the attributes are returned or not but the user who was expecting all the attributes end up having an output with limited attributes and can behave abruptly.

Instance: https://bugzilla.redhat.com/show_bug.cgi?id=1917253

**Comment by phlogistonjohn** [comment]
@agarwal-mudit can we close this? Or is there more work to do outside of issues #451 and #453. It's not clear to me.

**Comment by agarwal-mudit** [comment]
Yeah, I guess users need to take care of this rather fixing it in the library.
