### ISSUE TITLE
Add support to get rbd mirror image status

### ISSUE THREAD

**Issue by Madhu-1** [ceph/go-ceph#460]
This request is specific to a single API mentioned in https://github.com/ceph/go-ceph/issues/393

go-ceph does not support the `rbd mirror image status` to check the status of the image. This will help to check the Resync status of an image.

sample output

```
rbd mirror image status csi-vol-1d8f3426-4f5c-11eb-9989-0242ac110005 --pool=replicapool
csi-vol-1d8f3426-4f5c-11eb-9989-0242ac110005:
  global_id:   879ec6f1-5b39-4fd3-b380-632497bcf5c5
  state:       up+replaying
  description: replaying, {"bytes_per_second":0.0,"bytes_per_snapshot":0.0,"local_snapshot_timestamp":1611813784,"remote_snapshot_timestamp":1612953926,"replay_state":"syncing","syncing_percent":12,"syncing_snapshot_timestamp":1612953926}
  service:     a on cluster1
  last_update: 2021-02-10 11:10:21
  peer_sites:
    name: c2c57585-699b-4884-8e2c-12fcce5ad43d-rook-ceph
    state: up+replaying
    description: replaying, {"bytes_per_second":0.0,"bytes_per_snapshot":0.0,"remote_snapshot_timestamp":1612953931,"replay_state":"syncing","syncing_percent":12,"syncing_snapshot_timestamp":1612953931}
    last_update: 2021-02-10 11:10:28
```

**Comment by Madhu-1** [comment]
cc @phlogistonjohn @agarwal-mudit

**Comment by phlogistonjohn** [comment]
So this command appears to be based on different API functions depending on which ceph release is in use.
In nautilus this is image.mirror_image_get_status and in octopus this is image.mirror_image_get_global_status. These are C++ functions, there are C equivalents rbd_mirror_image_get_status & rbd_mirror_image_get_global_status. The functions also appear to make usre of the function to get the instance id (equivalent to rbd_mirror_image_get_instance_id).
On top of that the octopus version appears to be issuing mon_command calls with json command of `{"prefix": "service dump", "format": "json"}` and then processing the various results in utility functions.

Overall, this is a rather complex CLI command. From the pasted output it looks like you're using the octopus version.

Thus, I'd like to better understand exactly what you need from the command outputs so we can best target our work. @Madhu-1 let's discuss what in the current output of the command is required vs. nice to have so you can get what's most important to you first.

CC: @ansiwen

**Comment by Madhu-1** [comment]
@phlogistonjohn mainly looking at the below 3 fields in the status

```
state:       up+replaying
 description: replaying, {"bytes_per_second":0.0,"bytes_per_snapshot":0.0,"local_snapshot_timestamp":1611813784,"remote_snapshot_timestamp":1612953926,"replay_state":"syncing","syncing_percent":12,"syncing_snapshot_timestamp":1612953926}
  service:     a on cluster1
  last_update: 2021-02-10 11:10:21
```
the state is the important one for now. good to have description and last_update.

**Comment by phlogistonjohn** [comment]
Great thanks. I think state will be fairly reasonable. The "json" part of description may be tricky but we can look into it.
It helps a lot to know you're not looking for the "peer_sites" part ATM.
