### ISSUE TITLE
Support for contexts

### ISSUE THREAD

**Issue by immesys** [ceph/go-ceph#47]
I am having some difficulty dealing with propogating deadlines and handling timeouts (due to unhealthy cluster etc) at the application level. It would be great if there was a rados API that took a go `context` as the first parameter so that operations can express deadlines and do cancellations more cleanly. 

This issue is a request for comments, I am willing to do the work and do a PR but I am not familiar enough with rados to know if this lines up with how it is used in other languages or if it would be clean to implement. Any suggestions?

**Comment by noahdesu** [comment]
@immesys is this still relevant? i'm a little confused about what information you want to propagate to where. I'm probably just confused because I'm unaware of any deadline features in the rados API. Could you say a bit more about what you want to accomplish?

**Comment by phlogistonjohn** [comment]
Hello, I'm automatically closing all issues filed prior to 2018 that have not been commented on recently. If this issue is still relevant to you please reopen the issue and restart the discussion. Thank you for your understanding.
