### ISSUE TITLE
Provide string representation for mirroring modes

### ISSUE THREAD

**Issue by Madhu-1** [ceph/go-ceph#470]
https://github.com/ceph/go-ceph/blob/d75b75fb752bd189bcc476e111bd66290c58ab33/rbd/mirror.go#L26-L31 represents the mirroring mode in int format. currently, cephcsi cannot provide this int format to the user in response as it's not much help. if we have string representation it would be nicer for a user to check what is the current state.

**Comment by Madhu-1** [comment]
cc @phlogistonjohn @nixpanic

**Comment by phlogistonjohn** [comment]
Sure. Making the MirrorMode type meet the Stringer interface should be no major issue.
