### ISSUE TITLE
Missing rbd API components: function rbd_mirror_uuid_get

### ISSUE THREAD

**Issue by phlogistonjohn** [ceph/go-ceph#488]
The rbd API implements function(s) below but go-ceph does not:
* rbd_mirror_uuid_get

This issue has been filed to track implementing this missing
functionality in the appropriate package within go-ceph.
Please refer to the Ceph C API for details about the function(s)
in question.

NOTE: This issue was generated by a script.
If the content looks wrong or the wording seems a bit odd
please excuse the script and blame @phlogistonjohn

**Comment by rajatsing** [comment]
^^ @phlogistonjohn 
I can take this but after reading about it, I could not find many contexts about it, can you please give me some context over it?.
I read this https://docs.ceph.com/en/latest/rbd/rbd-mirroring/ but cannot find any information on `rbd_mirror_uuid_get`.

**Comment by phlogistonjohn** [comment]
> ^^ @phlogistonjohn
> I can take this but after reading about it, I could not find many contexts about it, can you please give me some context over it?.

Certainly!  


> I read this https://docs.ceph.com/en/latest/rbd/rbd-mirroring/ but cannot find any information on `rbd_mirror_uuid_get`.

Yeah, that's "user facing" or "admin facing" docs, we're working with the API directly and I never found formal docs for that.

One "shortcut" that I frequently use to help me think about how to wrap a function like this is to take a look at ceph's own python bindings in tree. In this case that'd be https://github.com/ceph/ceph/blob/77edcfdcdd732ce75987035a46d8c9a560e57b34/src/pybind/rbd/rbd.pyx#L1897

According to the pthon docstring, which appears accurate to me is to fetch the mirroring uuid for the pool associated with the ioctx. If we were to pretend the function was a command line tool it'd be something like:
```
$ mirror_uuid_get "poolName"
b326ea0a-e010-4ab2-ab22-2d242b84700f
```

There's a fair amount of additional stuff around mirroring in general but @ansiwen and I may also be able to help out with that over chat. In particular, once you've started wrapping the function we'll want to write tests using the "multi container" test that you can start from our makefile.

I hope this gets you started. If not, feel free to ping again here or over chat. Thanks!
