### ISSUE TITLE
rgw/admin: Provide an interface for debug logging

### ISSUE THREAD

**Issue by phlogistonjohn** [ceph/go-ceph#508]
Currently, the deubugging support in rgw/admin is directly connected to golang's log module. However, this library can and will be used from processes that have their own ideas about logging. We should decouple our library from any particluar logging lib by providing a simple interface. I see two choices:

1. Provide an interface that supports log methods we use:
```
type Logger interface {
    Printf(format string, v ...interface{})
}
```
This would need to set on the API type, either along with or replacing the "Debug" attribute.

2. Provide an interface around http client:
```
type HTTPClient interface {
       Do(*http.Request) (*http.Response, error)
}
```

This is much more flexible but lacks the "guide rails" of the previous approach. However you can do much more with it as any consumer of the lib can create a wrapper around the http client and inspect or track requests/responses, mutate, or mock the http interface.

We can provide an example wrapper type around *http.Client that does the logging.

**Comment by phlogistonjohn** [comment]
I prefer option 2, but do realize it can seem a bit too abstract. However, it proved very useful when we did something similar in the heketi project FWIW.

**Comment by leseb** [comment]
> I prefer option 2, but do realize it can seem a bit too abstract. However, it proved very useful when we did something similar in the heketi project FWIW.

I think I'll have to bring `type HTTPClient interface {}` once I start working on a MockClient for the `rgwadmin` package. But agree it won't be straightforward for consumers compared to the `Logger`.

**Comment by phlogistonjohn** [comment]
We could prove a copy and paste-able example tho. :-)

**Comment by phlogistonjohn** [comment]
@leseb it'd be nice if we could tackle this before the release on Aug. 10. If we have any additional points to discuss feel free to do it here.

**Comment by leseb** [comment]
@phlogistonjohn Sounds good. Even with the new Interface I'm failing to see how we can print dump the request just like we do with `DumpRequestOut()` and dump the response to `Do()` with `DumpResponse()`. Any pointers would be appreciated. Thanks.

**Comment by phlogistonjohn** [comment]
I envision something along these lines.

```go

type PrintfLogger interface {
    Printf(string,  ...interface{})
}

type DebugHTTPClient struct {
    client HTTPClient
    logger PrintfLogger
}

func NewDebugHTTPClient(client HTTPClient, logger PrintfLogger) *DebugHTTPClient {
    return &DebugHTTPClient{client, logger}
}

func (c *DebugHTTPClient) Do(req *http.Request) (*http.Response, error) {
    dump, err := httputil.DumpRequestOut(req, true)
    if err != nil {
        return nil, err
    }
     c.logger.Printf("\nrequest: %s\n", string(dump))

    resp, err := c.client.Do(req)
    if err != nil {
        c.logger.Printf("\nerror: %s\n", err)
        return nil, err
    }
    defer resp.Body.Close()

    dump, err = httputil.DumpResponse(resp, true)
    if err != nil {
        return nil, err
    }
    c.logger.Printf("\nresponse: %s\n", string(dump))
    return resp, nil
}
```

It doesn't need to be exactly like this but that's roughly the direction I'd head in.

In the example, I created a new PrintfLogger interface as a demonstration of decoupling the logging from the log package itself, however this isn't strictly required if this implementation lives in the tests.
