### ISSUE TITLE
rbd/admin: add calls to manage rbd tasks

### ISSUE THREAD

**Issue by phlogistonjohn** [ceph/go-ceph#516]
the `ceph` cli tools supports commands like:
* ceph rbd task add remove <img>
* ceph rbd task add flatten <img>
* ceph rbd task list [id]
* etc...

These can be done via the "json command" api for the mgr. We can support that functionality in rbd/admin.

**Comment by Madhu-1** [comment]
* `ceph rbd add task trash remove` Adding this command will also be helpful for ceph-csi

**Comment by Rakshith-R** [comment]
#577 adds support for flatten, remove and trash remove apis. 

support for remaining rbd task migration abort,commit,execute requires `ceph rbd migration` api support first. 
Opened #583 for it.

**Comment by phlogistonjohn** [comment]
@Rakshith-R should we be able to close this issue if all remaining tasks are tracked in #583?

**Comment by Rakshith-R** [comment]
> @Rakshith-R should we be able to close this issue if all remaining tasks are tracked in #583?

@phlogistonjohn  sure, I've edited the issue description to include remaining apis, we can close this issue.

**Comment by phlogistonjohn** [comment]
I am eventually consistent. Eventually.
