### ISSUE TITLE
create subuser in rgw

### ISSUE THREAD

**Issue by mfatemipour** [ceph/go-ceph#521]
hi, Is there any api to create subuser in rgw admin ?

**Comment by phlogistonjohn** [comment]
I don't think that's implemented yet, however it sounds like if your interested in using it via go-ceph that would be a good feature request.

CCing @leseb who's leading the effort on rgw admin.

**Comment by leseb** [comment]
@mfatemipour Hello, next time please consider using a Discussions thread for questions, we would like to keep Issues for bug report or feature request :).

Just like @phlogistonjohn mentioned the go-ceph project does not support creating subuser's yet.
Thanks!

**Comment by phlogistonjohn** [comment]
(Following up on things)
@mfatemipour & @leseb is this something we ought to track as an enhancement? If not - shall we close this issue?

**Comment by leseb** [comment]
> (Following up on things)
> @mfatemipour & @leseb is this something we ought to track as an enhancement? If not - shall we close this issue?

Eventually yes when the time permits it :)

**Comment by phlogistonjohn** [comment]
@leseb it's not clear to me which item you are saying yes to.

**Comment by leseb** [comment]
> @leseb it's not clear to me which item you are saying yes to.

I'm saying yes It can be done, it's just not tracked in the roadmap. It's not a large item though. I cannot just promise a timeline for it.

**Comment by phlogistonjohn** [comment]
Great. I will update the issue with the appropriate label. We generally don't expire feature requests but do eventually expire "questions". But this was unlabeled and in neither category.

We don't require timelines in go-ceph. Plus, so far no one's under any obligation to implement a particular request, but I find value in tracking what's been asked for.  Hope that all makes sense!

**Comment by leseb** [comment]
> Great. I will update the issue with the appropriate label. We generally don't expire feature requests but do eventually expire "questions". But this was unlabeled and in neither category.
> 
> We don't require timelines in go-ceph. Plus, so far no one's under any obligation to implement a particular request, but I find value in tracking what's been asked for. Hope that all makes sense!

Perfect sense!
