### ISSUE TITLE
How to exec command using go-ceph

### ISSUE THREAD

**Issue by liyang516** [ceph/go-ceph#529]
My goal is to execute the following command line：

1. ceph osd pool create k8s 128
2. ceph osd pool application enable k8s rbd
3. rbd pool init k8s
4. ceph auth get-or-create client.kubernetes mon 'profile rbd' osd 'profile rbd pool=k8s' mgr 'profile rbd pool=k8s'

I found function with "create pool" and "pool init"
but I do not found about "pool application enable" and "ceph auth"

Are there related functions in go-ceph？
Or is there a function in the code that can execute the ceph command line？

**Comment by phlogistonjohn** [comment]
I'm fairly certain we do not have functions equivalent to 'ceph auth ...' today. I need to research what 'ceph osd pool application enable' does to make a definitive answer but I suspect we don't do that yet either.

Many of the "ceph" commands use an API that exchanges JSON over a rados connection, and as such there are no C apis for these. Traditionally, go-ceph only wrapped the C api but we're slowly adding support for certain json-command APIs (see cephfs/admin and rbd/admin).

The general functions that are the basis for this JSON api are under rados and are named like MonCommand and MgrCommand. But until someone looks into it more what the commands and responses are as yet unknown.

Would you like me to tag (and probably split) this issue into feature requests?

**Comment by liyang516** [comment]
Tks，I have already resolve this question. The rados of MonCommand function is very powerful, it can help me achieve the above functions

**Comment by phlogistonjohn** [comment]
Good to hear. MonCommand is powerful indeed and very general :-)
Since you say the question is resolved, I'll close this issue. Feel free to reopen it if needed.
Do let us know if you find any issues or want specific features of the json-api wrapped in the future!
