### ISSUE TITLE
Implement wrapper for rbd_diff_iterate function(s)

### ISSUE THREAD

**Issue by pymhd** [ceph/go-ceph#53]
Hello,
Really appreciate  all work you've done but is there any chance of realization diff_iterate function in rbd package. 
Thanks.

**Comment by madbananas** [comment]
@pymhd  Absolutely agree, that would be really useful

**Comment by noahdesu** [comment]
@madbananas @pymhd just wanted to follow up on this issue. Is this still something you'd like supported?

**Comment by pymhd** [comment]
@noahdesu Absolutely. It would be really great. Thank you.

**Comment by phlogistonjohn** [comment]
@pymhd  @madbananas  please take a look at our PR #177 if you care to. This is your opportunity to check out the API we're adding and ask any q's about the design prior to us merging it. Thanks.
