### ISSUE TITLE
go get github.com/ceph/go-ceph

### ISSUE THREAD

**Issue by zakiournani** [ceph/go-ceph#54]
# github.com/ceph/go-ceph/rados
../github.com/ceph/go-ceph/rados/conn.go:5:11: fatal error: 'rados/librados.h' file not found
 #include <rados/librados.h>
          ^~~~~~~~~~~~~~~~~~
1 error generated.

**Comment by zeichenanonym** [comment]
https://github.com/ceph/go-ceph#installation states:

`The native RADOS library and development headers are expected to be installed.`

**Comment by zakiournani** [comment]
Are they available on MACOS, i only could install them on linux (Centos)
