### ISSUE TITLE
could not determine kind of name for C.rados_set_pool_full_try

### ISSUE THREAD

**Issue by bravelll** [ceph/go-ceph#555]
[root@node1 ceph]# go build  pool.go
# github.com/ceph/go-ceph/rados
/root/odev/src/github.com/ceph/go-ceph/rados/ioctx_octopus.go:23:2: could not determine kind of name for C.rados_set_pool_full_try
/root/odev/src/github.com/ceph/go-ceph/rados/ioctx_octopus.go:35:2: could not determine kind of name for C.rados_unset_pool_full_try

**Comment by phlogistonjohn** [comment]
Your local version of the ceph may not be "octopus". From the README:

> go-ceph tries to support different Ceph versions. However some functions might only be available in recent versions, and others may be deprecated. In order to work with non-current versions of Ceph, it is required to pass build-tags to the go command line. A tag with the named Ceph release will enable/disable certain features of the go-ceph packages, and prevent warnings or compile problems. ...


If you are using ceph from packages, you can use the package manager to get the ceph version and then backtrack to the release series code name. So if you are on ceph version 14, that's "nautilus". See this [ceph versions index](https://docs.ceph.com/en/latest/releases/index.html) for more details.

Once you do, use build tags to select the ceph version as noted on the readme.

Lastly, do note that the go-ceph's recent releases only support nautilus and newer.

**Comment by bravelll** [comment]
thanks!
