### ISSUE TITLE
compatibility issues between go-ceph@0.10.0 and ceph nautilus v14.2.11

### ISSUE THREAD

**Issue by iliul** [ceph/go-ceph#572]
hi  @ansiwen ,

When i use go-ceph@0.10.0 with ceph nautilus v14.2.11, I got the following error

```
# go run -tags nautilus quota.go
# github.com/ceph/go-ceph/cephfs
vendor/github.com/ceph/go-ceph/cephfs/file.go:309:33: could not determine kind of name for C.FALLOC_FL_KEEP_SIZE
vendor/github.com/ceph/go-ceph/cephfs/file.go:312:34: could not determine kind of name for C.FALLOC_FL_PUNCH_HOLE
```

I did some searching and found that it is because ceph nautilus v14.2.11 does not include the **FALLOC_FL_KEEP_SIZE** definition in `include/cephfs/ceph_ll_client.h`. This macro definition is introduced from https://github.com/ceph/ceph/pull/41580. I want to ask if it's needed backport this pr to the nautilus branch.

**Comment by iliul** [comment]
releate to #288 and #507

**Comment by ansiwen** [comment]
Hi @iliul, can you please specify on which platform you are building? These issues were only MacOS related.

**Comment by iliul** [comment]
> Hi @iliul, can you please specify on which platform you are building? These issues were only MacOS related.

@ansiwen I am using linux. The strange thing is that my machine has a falloc.h file at `/usr/include/linux/falloc.h`, and after I manually add it to vendor/github.com/ceph/go-ceph/cephfs/file.go the program works. I don’t know why it can’t find those symbols

**Comment by ansiwen** [comment]
@iliul these macros are Linux only, and they are only defined if `_GNU_SOURCE` is defined before. It seems like there is something unusual in your linux system. What distribution is that?

**Comment by iliul** [comment]
> @iliul these macros are Linux only, and they are only defined if `_GNU_SOURCE` is defined before. It seems like there is something unusual in your linux system. What distribution is that?

Thanks. It's a customized operating system based on CentOS Linux release 7.2, I will do some checks.

**Comment by ansiwen** [comment]
@iliul ok, so first make sure that as specified [here](https://man7.org/linux/man-pages/man2/fallocate.2.html) the macros are defined after

```c
#define _GNU_SOURCE
#include <fcntl.h>
```

in a test C program.

**Comment by iliul** [comment]
> @iliul ok, so first make sure that as specified [here](https://man7.org/linux/man-pages/man2/fallocate.2.html) the macros are defined after
> 
> ```c
> #define _GNU_SOURCE
> #include <fcntl.h>
> ```
> 
> in a test C program.

@ansiwen Thanks, I found the root cause of the problem, I tried to upgrade the glibc & glibc-headers version from 2.17-196 to 2.17-323 and the problem was solved. 🤣

**Comment by ansiwen** [comment]
Alright, thanks for the feedback. I'll close this issue then.
