### ISSUE TITLE
apiage: add links to documentation

### ISSUE THREAD

**Issue by phlogistonjohn** [ceph/go-ceph#592]
I had meant to add hyperlinks to the "official" go docs for go ceph when our tool generates the markdown table of deprecated and preview APIs. But I never got around to it. It should be straightforward use of the pkg name and `[<type>.]>func>` after the anchor (`#`)`.

**Comment by ansiwen** [comment]
Preview APIs don't have docs and deprecated APIs should not be used, so I would vote for not doing that.

**Comment by phlogistonjohn** [comment]
At one point I was looking into how we could generate our own static docs and use that to supplement the online docs. Unfortunately, while there is some existing tooling to do so it appeared unmaintained and there doesn't seem to be a lot of interest in that approach currently.

That said I haven't completely given up on the idea.

**Comment by phlogistonjohn** [comment]
I'm OK with closing the issue. Issue #601 tracks the problem with the preview tags/apis, as well as some of my previous comments about static generation.  If #601 is ever solved *then* we can revisit the idea (or just combine them?).

**Comment by anoopcs9** [comment]
> Preview APIs don't have docs and deprecated APIs should not be used, so I would vote for not doing that.

I second that.

> I'm OK with closing the issue. Issue #601 tracks the problem with the preview tags/apis, as well as some of my previous comments about static generation. If #601 is ever solved _then_ we can revisit the idea (or just combine them?).

Hm.. let's just close it for now.
