### ISSUE TITLE
cephfs admin: wrap subvolume pinning API

### ISSUE THREAD

**Issue by phlogistonjohn** [ceph/go-ceph#611]
See https://github.com/ceph/ceph-csi/issues/2637
& ceph/ceph#43896

This is soon-to-be-document CLI (and matching JSON command api) that ceph-csi would like to use. See the above items for details.

**Comment by humblec** [comment]
I can work on this

**Comment by phlogistonjohn** [comment]
Hi, @humblec I was going through some older issues and saw this. I was looking for some things for @anoopcs9 to look into - and this seemed like a good candidate. But I just want to double check that you weren't already working on it first. Thanks!

**Comment by humblec** [comment]
> Hi, @humblec I was going through some older issues and saw this. I was looking for some things for @anoopcs9 to look into - and this seemed like a good candidate. But I just want to double check that you weren't already working on it first. Thanks!

Thanks for checking ! sure, reassigning to @anoopcs9 .

**Comment by humblec** [comment]
Also, it looks like there are requests to prioritize this, so it would be great if we can get this in next go -ceph release so that Ceph CSI can consume as well.
