### ISSUE TITLE
rgw: admin/README.md shows incorrect usage of co.GetUser(...)

### ISSUE THREAD

**Issue by rakeshgm** [ceph/go-ceph#617]
[README.md](https://github.com/ceph/go-ceph/blob/master/rgw/admin/README.md) has incorrect usage of `co.GetUser(...)`

`co.GetUser(..)` has parameters of type `context` and `User`, but the example shows that we need to use a `context` and a `string`  like this, `co.GetUser(context.Background(), "admin")`, which is incorrect. 

[reference](https://github.com/ceph/go-ceph/blob/master/rgw/admin/user.go#L60)

**Comment by phlogistonjohn** [comment]
Thanks. @rakeshgm would you be interested in contributing a doc fix this yourself?  CCing @leseb for awareness.

**Comment by rakeshgm** [comment]
sure @phlogistonjohn , i can contribute, there is one other issue that is blocking me from testing this. once I get clarity on this. I will send the patch. #619

**Comment by rakeshgm** [comment]
fix is in this PR  https://github.com/ceph/go-ceph/pull/620
