### ISSUE TITLE
rgw: conn.ListBuckets() gives access denied when used with correct s3 creds

### ISSUE THREAD

**Issue by rakeshgm** [ceph/go-ceph#619]
I want to list all the buckets in a user. I have a small snippet, here

```
func rgwConnect() {
	endpoint := "http://192.168.0.1:80" 
	accesskey := "access_key"
	secretkey := "secret_key"
 
	conn, err := admin.New(endpoint, accesskey, secretkey, nil)
 
	if err != nil {
		fmt.Println("got err1:", err)
		return
	}
 
	buckets, err2 := conn.ListBuckets(context.Background())
	if err2 != nil {
		fmt.Println("got err2:", err2)
		return
	}
 
	fmt.Println(buckets)
 
}
```
And when I run this snippet, i allways get 
`err2: AccessDenied tx000000000000000000030-0061b0f549-1031-default 1031-default-default` 

However, I am able to create buckets and list buckets using boto with the same credentials.

**Comment by rakeshgm** [comment]
@leseb thanks for the hint,  the user that I created did not have any caps, I then added `--caps="users=*;buckets=*"` 
then `conn.ListBuckets()` worked, got buckets list.  
but I wonder why list buckets worked from `boto`, `s3cmd` and from `radosgw-admin bucket list --uid <userid>` without the caps

**Comment by leseb** [comment]
> @leseb thanks for the hint, the user that I created did not have any caps, I then added `--caps="users=*;buckets=*"` then `conn.ListBuckets()` worked, got buckets list. but I wonder why list buckets worked from `boto`, `s3cmd` and from `radosgw-admin bucket list --uid <userid>` without the caps

For this `radosgw-admin bucket list --uid <userid>`, the answer is easy, the command is using the admin credentials to list that user's bucket. For boto and s3cmd I don't know, but if no caps were granted it's expected that they don't work.

I'm closing this since the issue has been resolved, thanks!
