### ISSUE TITLE
cephfs: Add wrapper to consume 'ceph fs volume info' command.

### ISSUE THREAD

**Issue by nmshelke** [ceph/go-ceph#695]
cephfs team is planning to add API to show information of volume.
Please find pull request regarding this: https://github.com/ceph/ceph/pull/45949

**Comment by vshankar** [comment]
Command output fields are available in document - https://github.com/ceph/ceph/pull/45949/files#diff-45f83f814dee15dc10b8025029c5400a50e6c8972d5b6a795b62d62e0b278986R100

**Comment by anoopcs9** [comment]
https://docs.ceph.com/en/latest/cephfs/fs-volumes/#fs-volumes
