### ISSUE TITLE
Missing rados API components: function rados_set_alloc_hint

### ISSUE THREAD

**Issue by Okhoshi** [ceph/go-ceph#697]
The rados API implements function(s) below but go-ceph does not:
- rados_set_alloc_hint
- rados_set_alloc_hint2
- rados_write_op_set_alloc_hint
- rados_write_op_set_alloc_hint2

Please refer to the Ceph C API for details about the function(s) in question.

We would like to be able to use these functions, and are also willing to contribute if it can help to make these into the lib. 👍

**Comment by phlogistonjohn** [comment]
That sounds good to me. Please note that most of the time foo_bar2 API calls are super-sets of the functionality of foo_bar calls in the C API. This means that for go-ceph you *usually* only need to implement the foo_bar2 version of the call. 

We very much welcome contributions.  With an issue, we maintainers may have time for adding the requested feature some time in the future.  But if you contribute changes, you are much more in control of when your desired feature might be available in a release. :-)

If you're not 100% about the approach or you just want to share a "rough sketch" or prototype feel free to file a Draft PR and we'll try to coach you a bit if you'd like that. New features are considered "preview" when they're first added - the api policies are documented [here](https://github.com/ceph/go-ceph/blob/master/docs/api-stability.md) and [here](https://github.com/ceph/go-ceph/blob/master/docs/development.md#documentation-conventions).
Don't hesitate to ask questions if you've got any.
