### ISSUE TITLE
 How can set a quota for a pool ？

### ISSUE THREAD

**Issue by holidayun** [ceph/go-ceph#709]
i use 
```
m := map[string]string{
    "prefix":"osd pool set-quota", 
    "pool": "bob", 
    "max_bytes": "$((8 * 1024 * 1024 * 1024))"
}
```
I got error : rados: ret=-22, Invalid argument

**Comment by phlogistonjohn** [comment]
Here's part of JSON dump that the ceph command uses to determine what mon commands exist:
```json
  "cmd591": {
    "sig": [
      "osd",
      "pool",
      "set-quota",
      { 
        "name": "pool",
        "type": "CephPoolname"
      },
      { 
        "name": "field",
        "strings": "max_objects|max_bytes",
        "type": "CephChoices"
      },
      { 
        "name": "val",
        "type": "CephString"
      }
    ],
    "help": "set object or byte limit on pool",
    "module": "osd",
    "perm": "rw",
    "flags": 0
  },
```


This indicates that your examples the prefix and pool parameters look OK. However there are issues with the remaining items. First, the name of the 2nd argument is `field` and it takes a value of either `max_objects` or `max_bytes`.  Next, you appear to have embedded "shell math" in your Go code. This is the `$(( ... ))` part.  When you run the ceph command on the command line this math is taken care of by your shell (eg. bash) its not part of the ceph command or the ceph server.  You need to calculate the value that you want and put it in as a stringified integer  (example: "8589934592").

So I would expect the map value to look more like:
```golang
m := map[string]string{
    "prefix":"osd pool set-quota", 
    "pool": "bob", 
    "field": "max_bytes",
    "val": "8589934592",
}
```

Convert that to JSON and see it that works better.  Hope this helps.

**Comment by holidayun** [comment]
Tank you for your answer， I use `{"prefix": "get_command_descriptions"}` got all  command
In results, set pg_num command is `{"prefix":"osd pool create", "pool": "bob", "pg_num":"10"}`
I got error : `rados: ret=-22, Invalid argument`
when i use` {"prefix":"osd pool create", "pool": "bob", "pg-num":"10"}`
No error displayed, but pg_num is not used
