### ISSUE TITLE
libcephfs change in `statx` flags causes failure in running tests

### ISSUE THREAD

**Issue by anoopcs9** [ceph/go-ceph#741]
While trying to run our test suite(`make test-containers-test`) against pre-release version of quincy following failure was seen:
```
cephfs/statx.go:58:25: could not determine kind of name for C.AT_NO_ATTR_SYNC
```

With https://github.com/ceph/ceph/pull/45844, `statx` flag in question no longer exists and causes the above mentioned failure. Backport for pacific is also merged.

**Comment by phlogistonjohn** [comment]
Filed an issue at ceph: https://tracker.ceph.com/issues/56638

I'd prefer to fix this in ceph as it may impact other projects using libcephfs. If the cephfs team chooses not to see this as an issue needing a fix we'll have to work around it with build tags, but I hope they agree to fix this in ceph first.

**Comment by lxbsz** [comment]
This sounds good to me and I will raise one PR to fix it.

**Comment by phlogistonjohn** [comment]
https://github.com/ceph/ceph/pull/47182 <-- ceph PR.
thanks a bunch @lxbsz !

**Comment by ansiwen** [comment]
> [ceph/ceph#47182](https://github.com/ceph/ceph/pull/47182) <-- ceph PR. thanks a bunch @lxbsz !

I don't see, how this is a fix for us? I mean, sure, it doesn't break anymore _right now_, but it is still deprecated and will be removed eventually. If this is earlier than when we remove nautilus (which we just introduced new stuff for) we still need to handle both cases simultaneously. So I would rather suggest that we also deprecate `AtNoAttrSync`, replace it with `AtStatxDontSync`, and add something like 
```C
#ifndef AT_STATX_DONT_SYNC
#define AT_STATX_DONT_SYNC AT_NO_ATTR_SYNC
#endif
```
in the C stub.
