### ISSUE TITLE
connect  with ReadConfigFile get error ： ret=-13, Permission denied 

### ISSUE THREAD

**Issue by holidayun** [ceph/go-ceph#744]
my code 
```
configPath := "/home/config/ceph.conf"
conn, _ := rados.NewConn()
if err := conn.ReadConfigFile(configPath); err != nil {
    return nil, err
}
if err := conn.Connect(); err != nil {
    return nil, err
}
```

There is a file of ceph.conf in /home/config, like this

```
# minimal ceph.conf for 21c80fea-d594-11ec-97b4-5254a8d6abe6
[global]
        fsid = 21c80fea-d594-11ec-97b4-5************
        mon_host = [v2:111.1111.22.110:3300/0,v1:111.1111.22.110:6789/0] [v2:111.1111.22.111:3300/0,v1:111.1111.22.111:6789/0] [v2:111.1111.22.113:3300/0,v1:111.1111.22.113:6789/0]
```

when i run code in ceph's master host, connect success
but when i run in  other host，such as 111.111.22.888， got error： ret=-13, Permission denied
Looking forward to your answer

**Comment by phlogistonjohn** [comment]
I'm not sure if you meant to anonymize the fsid, but you didn't do it in all places, JFYI. 

Without knowing more about the network this might be a tough one to diagnose. My suggestion would be to edit your conf file to enable more logging from the ceph libs and see what they may be hinting at.
You can read the last part of [my old blog post here](http://asynchrono.us/how-i-work-on-go-ceph.html)  for some hints on how to enable this logging.

**Comment by holidayun** [comment]
When connecting the ceph cluster, do not need to transfer "ceph. Client. Admin. The keyring" file?

**Comment by holidayun** [comment]
Problem solved。
frist：  conn.ReadConfigFile(configPath)
second： conn.ReadConfigFile(keyringPath)
Thank you for your answer~~
