### ISSUE TITLE
go-ceph release tags

### ISSUE THREAD

**Issue by isi-lincoln** [ceph/go-ceph#75]
I would like to introduce the topic of having releases for go-ceph.  This would also be related to https://github.com/ceph/go-ceph/issues/70 in the sense of dependency versioning.

For many this will act as a point of stability for CI/CD where pegged code releases can be used instead of relying on master branch.  As good as a practice of writing tests for code, there is always the chance for new bugs to be introduced.  Having release versions would help go-ceph users from introducing bugs that may be introduced via the master branch.

`dep` (https://github.com/golang/dep) is one such tool that allows dependencies to be versioned to reduce the risk of introducing bugs into stable versions of go-ceph.

**Comment by dswarbrick** [comment]
This was already discussed in #72.

**Comment by isi-lincoln** [comment]
I dont see any mention of having release tags - only which package manager to use.  This is tangential to the package management.

**Comment by dswarbrick** [comment]
I was referring to your `dep` suggestion.

**Comment by isi-lincoln** [comment]
Apologies, i meant to use it as an example for why release tags would be helpful.

**Comment by phlogistonjohn** [comment]
The initial "0.2" release is currently planned for 2020-02-11.

**Comment by phlogistonjohn** [comment]
https://github.com/ceph/go-ceph/releases/tag/v0.2.0
Please open new issues for anything pertaining to the release content or process itself. Thanks!
