### ISSUE TITLE
Remove ceph_pre_quincy tags from cephfs/admin metadata and snap metadata apis

### ISSUE THREAD

**Issue by phlogistonjohn** [ceph/go-ceph#752]
Once the following changes are available in a quincy (or earlier?) **release**.

https://tracker.ceph.com/issues/54472
https://tracker.ceph.com/issues/55401

**Comment by anoopcs9** [comment]
> https://tracker.ceph.com/issues/54472

[Quincy](https://github.com/ceph/ceph/pull/45994) backport merged.
Pacific backport is pending.

> https://tracker.ceph.com/issues/55401

[Pacific](https://github.com/ceph/ceph/pull/46515) and [Quincy](https://github.com/ceph/ceph/pull/46508) backports are merged.

**Comment by anoopcs9** [comment]
> > https://tracker.ceph.com/issues/54472
> 
> [Quincy](https://github.com/ceph/ceph/pull/45994) backport merged. Pacific backport is pending.

My bad. I failed to find the [Pacific](https://github.com/ceph/ceph/pull/45961) backport last time. 
 
> > https://tracker.ceph.com/issues/55401
> 
> [Pacific](https://github.com/ceph/ceph/pull/46515) and [Quincy](https://github.com/ceph/ceph/pull/46508) backports are merged.
