### ISSUE TITLE
`make check` fails in CI

### ISSUE THREAD

**Issue by anoopcs9** [ceph/go-ceph#754]
Latest [release](https://github.com/mgechev/revive/releases/tag/v1.2.2) for `revive` [increased](https://github.com/mgechev/revive/pull/694) the confidence value for _package-comments_ rule from **0.2** to **1** resulting in `check-revive` failure.
```
$ make check-revive
# Configure project's revive checks using .revive.toml
# See: https://github.com/mgechev/revive
revive -config .revive.toml $(find . -name '*.go')
./cephfs/command.go:1:1: should have a package comment
./rbd/errors.go:1:1: should have a package comment
./rados/rados_write_op_assert_version.go:1:1: should have a package comment
. . .
./rados/rados.go:1:1: should have a package comment
./rbd/snapshot_namespace.go:4:1: should have a package comment
./rados/ioctx.go:1:1: should have a package comment
make: *** [Makefile:229: check-revive] Error 1
```

**Comment by anoopcs9** [comment]
Options going forward:

* Restrict `revive` @ v1.2.1
* Raise confidence value above `1.0`
* Reduce severity for `[rule.package-comments]`
* Remove `[rule.package-comments]`

**Comment by anoopcs9** [comment]
> Missing option:
> 
>     * Add doc comments to the packages that lack them.

Possible but then I realized that we have `$(find . -name '*.go')` in Makefile for `check-revive`. How about using `go list ./...` instead?
```diff --git a/Makefile b/Makefile
index 9377d26..03498fb 100644
--- a/Makefile
+++ b/Makefile
@@ -226,7 +226,7 @@ check-format:
 check-revive:
        # Configure project's revive checks using .revive.toml
        # See: https://github.com/mgechev/revive
-       revive -config .revive.toml $$(find . -name '*.go')
+       revive -config .revive.toml $$($(GO_CMD) list ./... | grep -vE 'contrib|internal')
 
 check-shell:
        shellcheck -fgcc $(SHELL_SOURCES)
```
```
$ make check-revive
# Configure project's revive checks using .revive.toml
# See: https://github.com/mgechev/revive
revive -config .revive.toml $(go list ./... | grep -vE 'contrib|internal')
```

**Comment by anoopcs9** [comment]
> Possible but then I realized that we have `$(find . -name '*.go')` in Makefile for `check-revive`. How about using `go list ./...` instead?

just saw https://github.com/ceph/go-ceph/pull/640 🙄

**Comment by phlogistonjohn** [comment]
I'm assigning it to myself. Later today I'll add package level doc comments for the packages that don't have them.

**Comment by phlogistonjohn** [comment]
Now that I'm looking more deeply at it, it seems to be failing to detect package comments that do exist. I tried tweaking the comment formatting but that didn't help.

I'm thinking about filing an issue with revive. We may need one of those workarounds in the short term.

**Comment by phlogistonjohn** [comment]
While going through the checklist for revive's issue submissions I noticed our github action for running make check was using an old version of Go. Investigating that in case that is helping cause some of the false positives.

**Comment by phlogistonjohn** [comment]
So I think I went through all the steps you did in a 2nd loop. I decided that this check is now more trouble than it's worth and have disabled it.  See the linked PR.

If in the future revive grew options for setting build tags (https://github.com/mgechev/revive/issues/230  -- currently revive's oldest open issue :-) )  we could reconsider this and pass package dirs on the command line rather than files but I would rather have all the files checked automatically with the remaining rules than constantly have to deal with these false positives, or some other complicated way of invoking revive.

**Comment by anoopcs9** [comment]
> If in the future revive grew options for setting build tags ([mgechev/revive#230](https://github.com/mgechev/revive/issues/230) -- currently revive's oldest open issue :-) ) we could reconsider this and pass package dirs on the command line rather than files but I would rather have all the files checked automatically with the remaining rules than constantly have to deal with these false positives, or some other complicated way of invoking revive.

I agree. Thanks for going through the details.
