### ISSUE TITLE
uid is missing from usage type in GetUsage method

### ISSUE THREAD

**Issue by amirhaa** [ceph/go-ceph#758]
``uid`` is marked as valid params but it is missing from ``Usage`` struct type.

https://github.com/ceph/go-ceph/blob/9d74c3c2b1a08ad171d14bb78cc59273434030e3/rgw/admin/usage.go#L54

https://github.com/ceph/go-ceph/blob/9d74c3c2b1a08ad171d14bb78cc59273434030e3/rgw/admin/usage.go#L11-L49

**Comment by phlogistonjohn** [comment]
CC: @thotz  @leseb

**Comment by thotz** [comment]
@amirhaa: It is definitely a bug, IMO API was written to collect the total objectstore usage than the individual user, but passed uid in the request.  We modify the `usage` struct and `GetUsage()` API to support both use cases or only the object store. In the later case, may need to add new API for individual use cases.
