### ISSUE TITLE
function deprecated 

### ISSUE THREAD

**Issue by HeyIns** [ceph/go-ceph#76]
Hi Noah: I am developing a object storage system using the rados object in ceph by your go-ceph on github. But when I compile my go script ,I get a warning that the function rados_read_op_omap_get_vals in librados.h:3389 is deprecated which is used in your go-ceph/rados/ioctx.go:453.Maybe you should use the rados_read_op_omap_get_vals2 according to librados.h:3395

**Comment by ZYecho** [comment]
Got the same error on ubutnu 18.04

**Comment by MalloZup** [comment]
Close this issue
