### ISSUE TITLE
Question: dependency version

### ISSUE THREAD

**Issue by ZYecho** [ceph/go-ceph#79]
I want to know that if there' s version limit about the dependency(libcephfs-dev librbd-dev librados-dev), I  install the go-ceph and run example in ubuntu 16.04 and ubuntu18.04, both not worked.

In ubuntu 16.04, got same issue with #78 , and I find that the libcephfs-dev 12.x.x only available in  ubuntu18.04, but in 18.04 got another issue same with #76 .

So I want to ask, is there a dependency version limitation or os limitation?
Could you help me to use go-ceph? I can give more details if you want.

**Comment by noahdesu** [comment]
we currently only test with luminous (ver 12.2.x) and mimic (ver 13.2.x). are you using one of those versions of ceph client libraries? post your errors here and we can help figure it out. if you are using an older version, it'd definitely be easiest to upgrade your local version. if you need to use an older version, that's a different discussion.

**Comment by ZYecho** [comment]
Thanks, I think this info  need to update in the README.

**Comment by senthilrag** [comment]
Ran into same issue with Xenial. Note on upgrading to newer revision thought might be useful. Shown below is an example with "mimic" version.  

Reference: 
http://docs.ceph.com/docs/mimic/start/quick-start-preflight/#advanced-package-tool-apt

1) update the apt source list:

cat /etc/apt/sources.list.d/ceph.list
deb https://download.ceph.com/debian-mimic/ xenial main
deb-src https://download.ceph.com/debian-mimic/ xenial main

2) apt-get update

3) apt install libcephfs-dev librbd-dev librados-dev
