### ISSUE TITLE
rgw/get all buckets with stats

### ISSUE THREAD

**Issue by TheMoti** [ceph/go-ceph#800]
Hi ceph team,

We had an issue using `rgw`. Our requirement was to get all buckets with their stats (like it was possible in [Quentin's `GetBucket`](https://github.com/QuentinPerez/go-radosgw/blob/master/pkg/api/helpers.go)), but `ListBuckets` only return bucket names and calling `GetBucketInfo` on all listed buckets has too much overhead. Can you add a function which lists all buckets with their stats or with optional params? I can create the merge request if it's a valid function for this lib.

Thank you :)

**Comment by phlogistonjohn** [comment]
CCing @thotz who's been doing most of the rgw package maintenance lately.

**Comment by thotz** [comment]
> Hi ceph team,
> 
> We had an issue using `rgw`. Our requirement was to get all buckets with their stats (like it was possible in [Quentin's `GetBucket`](https://github.com/QuentinPerez/go-radosgw/blob/master/pkg/api/helpers.go)), but `ListBuckets` only return bucket names and calling `GetBucketInfo` on all listed buckets has too much overhead. Can you add a function which lists all buckets with their stats or with optional params? I can create the merge request if it's a valid function for this lib.
> 
> Thank you :)

IMO it is already addressed via https://github.com/ceph/go-ceph/blob/master/rgw/admin/user_bucket.go#L43
Are you looking for more generic, list all the buckets from all different users, if yes then you can totally send a PR. I am very happy to review the changes.

**Comment by TheMoti** [comment]
> > Hi ceph team,
> > We had an issue using `rgw`. Our requirement was to get all buckets with their stats (like it was possible in [Quentin's `GetBucket`](https://github.com/QuentinPerez/go-radosgw/blob/master/pkg/api/helpers.go)), but `ListBuckets` only return bucket names and calling `GetBucketInfo` on all listed buckets has too much overhead. Can you add a function which lists all buckets with their stats or with optional params? I can create the merge request if it's a valid function for this lib.
> > Thank you :)
> 
> IMO it is already addressed via https://github.com/ceph/go-ceph/blob/master/rgw/admin/user_bucket.go#L43 Are you looking for more generic, list all the buckets from all different users, if yes then you can totally send a PR. I am very happy to review the changes.

Hi again,
Yes, I meant an API to get all users buckets detail [for admin to use]. I'll send a PR but the changes are quite minor and similar to `GetUsersBuckets`. Please check it out, I hope I didn't get it all wrong.
Thanks
