### ISSUE TITLE
Is go-ceph support arm？ 

### ISSUE THREAD

**Issue by haroldHT** [ceph/go-ceph#807]
Env: 4.18.0-408.el8.aarch64（uname -r）
Pre: yum install libcephfs-dev librbd-dev librados-dev 
Build: go build -o ceph_exporter -tags nautilus
```
Error: 
# github.com/ceph/go-ceph/rados
/root/go/pkg/mod/github.com/ceph/go-ceph@v0.19.0/rados/ioctx.go:706:9: could not determine kind of name for C.rados_ioctx_get_namespace
```

**Comment by phlogistonjohn** [comment]
There's no reason ARM shouldn't work. However, we do not test on arm. What distro are you using? What version of ceph got installed (rpm -q librados-dev)?  Depending on distro the packages may be named *-devel rather than *-dev FWIW, example: `librados-devel`.

**Comment by haroldHT** [comment]
Thanks for ur reply, 
`rpm -qa|grep rados
librados2-12.2.8-8.p03.ky10.aarch64
librados-devel-12.2.8-8.p03.ky10.aarch64

rpm -qa|grep libcephfs
libcephfs-devel-12.2.8-8.p03.ky10.aarch64
libcephfs2-12.2.8-8.p03.ky10.aarch64

rpm -qa|grep librbd
librbd-devel-12.2.8-8.p03.ky10.aarch64
librbd1-12.2.8-8.p03.ky10.aarch64
`

**Comment by haroldHT** [comment]
I upgrade my librados, and go build it, now:
go build -o ceph_exporter -tags nautilus
```
# github.com/ceph/go-ceph/rados
/root/go/pkg/mod/github.com/ceph/go-ceph@v0.19.0/rados/ioctx_set_alloc_hint.go:24:114: undefined: AllocHintFlags
/root/go/pkg/mod/github.com/ceph/go-ceph@v0.19.0/rados/write_op_set_alloc_hint.go:19:96: undefined: AllocHintFlags

**Comment by phlogistonjohn** [comment]
OK, you've made progress and now you are encountering Issue #798 - please try the workarounds documented there.

**Comment by anoopcs9** [comment]
@haroldHT Were you able to make progress here?
