### ISSUE TITLE
cephfs.admin.New is missing Shutdown

### ISSUE THREAD

**Issue by aep** [ceph/go-ceph#816]
it looks like RadosCommander is a regular rados connection, which should be shutdown i think,

but when you use the convenience function admin.New, it doesnt expose the RadosCommander, so you cant shut it down

**Comment by phlogistonjohn** [comment]
Excellent point, thank you for reporting this issue.

Looking at the other admin sub-packages: rbd/admin, common/admin/nfs, common/admin/manager - we did not add a New function that sets up the rados connection internally. We only provided NewFromConn functions.
That leads me to think that our best course of action is to deprecate and eventually remove the (cephfs admin) admin.New function.  That may be slightly less convenient but it simplifies the approach and makes cephfs/admin more like the other admin packages.

Regardless of how we attempt to resolve this issue I suggest using NewFromConn in the meantime, thanks!
