### ISSUE TITLE
mount non-default mds_namespace/volume by name 

### ISSUE THREAD

**Issue by aep** [ceph/go-ceph#818]
with [cephfs.CreateFromRados](https://pkg.go.dev/github.com/ceph/go-ceph@v0.19.0/cephfs#CreateFromRados) i get a MountInfo for the default volume, (i think). 

how do i use a different volume?

i think the C api might be `ceph_select_filesystem` ?

**Comment by aep** [comment]
probably DUP of #262 

can i just send a PR to implement it?

**Comment by phlogistonjohn** [comment]
> probably DUP of #262
>

I agree that API is what you need to implement. 
 
> can i just send a PR to implement it?

Certainly, and it looks like you already did. That's great, thanks!
