### ISSUE TITLE
Update CI runs for current go version(s)

### ISSUE THREAD

**Issue by phlogistonjohn** [ceph/go-ceph#825]
With the release of Go 1.20 we are a bit out of date with our test Go version. Generally we want to make sure we test will all supported Go versions, which means defaulting to latest-1, and now that'd be 1.19.

Currently, the Dockerfile defaults to 1.17.9

**Comment by ansiwen** [comment]
If we want to test with _all_ supported Go versions we would have to test with 1.19 _and_ 1.20. Is that what you meant?

**Comment by phlogistonjohn** [comment]
That's not what I meant. I should not have written 'all'.  We want to make sure go-ceph compiles with supported go versions. Since n-1 is always supported we default to testing with n-1. 
That's currently 1.19. We missed updating to 1.18.
(Honestly, I have trouble phrasing this... so I hope this makes sense)

As *extra credit* and not for this issue. I'd be open to expanding the CI to test both supported go versions. BUT! We'd then need to discuss the matrix of go + ceph versions and if we really want to kick off >=2*6 CI jobs for every PR.  If you're interested in this task, please file a new issue for that topic :-)

(I counted the number of ceph branches we test in my head. It's probably not accurate. But I do think I counted at least a complete subset of theuilds.
