### ISSUE TITLE
Question: rados connect timeout arg

### ISSUE THREAD

**Issue by iawia002** [ceph/go-ceph#85]
Hi there, I'm wondering if there are any parameters or some other ways that can control the rados connection timeout.

For example, when I set the wrong monitor address in args, `conn.Connect()` takes 5 minutes to time out, it's too long.

I tried `--connect-timeout`, but it doesn't work

```go
conn, err := rados.NewConnWithUser(user)
...
args := []string{"--connect-timeout", "10", ...}
conn.ParseCmdLineArgs(args)
conn.Connect()
```

**Comment by noahdesu** [comment]
Does it still take 5 minutes with that option,  or does something else happen?

**Comment by iawia002** [comment]
Yes, with or without this `--connect-timeout` option, it always takes 5 minutes to timeout

**Comment by ioito** [comment]
try rados_osd_op_timeout rados_mon_op_timeout client_mount_timeout

**Comment by iawia002** [comment]
@ioito Thanks, `client_mount_timeout` works
