### ISSUE TITLE
rbd: mirror_peer_site.go exposes C type `time_t` to public api

### ISSUE THREAD

**Issue by phlogistonjohn** [ceph/go-ceph#870]
I missed this in review, but that's why we have `ceph_preview`.  :-)

Generally, we've avoided implementation defined C types like `time_t` in our public APIs. We should update MirrorPeerSite to expose LastSeen only as a Go integer type, a Go time type, or some other Go friendly struct type.  Go consumers "can't" work directly with time_t values.

**Comment by phlogistonjohn** [comment]
@Nikhil-Ladha  since you recently added this file are you interested in fixing this issue? If not, don't hesitate to say so. It shouldn't be hard to find a maintainer who's free to fix this before next release.

**Comment by Nikhil-Ladha** [comment]
Sure, made a PR for it :)
