### ISSUE TITLE
Support crush manager

### ISSUE THREAD

**Issue by dheart-joe** [ceph/go-ceph#897]
now, we want to edit  crush with golang.but, I found ceph has not support crush_map update by golang.
hope go-ceph can provide APIs.

**Comment by phlogistonjohn** [comment]
Thanks for the request. However, I would appreciate it if you could provide a bit more detail. Currently, go-ceph focuses on providing wrappers for APIs that ceph exports (in C) for Go. We also have the "admin" packages that use the APIs to call "JSON command" APIs on the Ceph MGR.  If there are existing C APIs for editing the CRUSH Map we can certainly look into wrapping them. If you're looking for something else we'll need more information about what you want.

**Comment by dheart-joe** [comment]
Such as golang struct decode/encode into the crush map, that is  the bufferlist of the command response that "ceph osd get crushmap" . Thank you for your response!
