### ISSUE TITLE
Missing rbd API components: function peer_site_remove

### ISSUE THREAD

**Issue by gyunn35** [ceph/go-ceph#901]
I couldn't find a function that wraps the `peer_site_remove` function. I need a function to remove the added peer. Is there another function?

**Comment by anoopcs9** [comment]
We do have [RemovePeerMirrorSite](https://github.com/ceph/go-ceph/blob/master/rbd/mirror_peer_site.go#L64) API in preview state which is set to become stable by next(v0.23.0) release. Find more on how APIs are tagged differently from our [API Stability docs](https://github.com/ceph/go-ceph/blob/master/docs/api-stability.md) and [API Status docs](https://github.com/ceph/go-ceph/blob/master/docs/api-status.md).

Does that help you here?

**Comment by gyunn35** [comment]
Sorry for not looking carefully. Helped me a lot.
