### ISSUE TITLE
macos m1pro fatal error: 'rados/librados.h' file not found

### ISSUE THREAD

**Issue by itxiaolin** [ceph/go-ceph#902]
ceph-client has been installed

ceph -v
ceph version 17.2.5 (98318ae89f1a893a6ded3a640405cdbb33e08757) quincy (stable)

 go build -tags quincy
# github.com/ceph/go-ceph/rados
/Users/linxianqin/go/pkg/mod/github.com/ceph/go-ceph@v0.22.0/rados/alloc_hint_flags.go:4:11: fatal error: 'rados/librados.h' file not found
 #include <rados/librados.h>
          ^~~~~~~~~~~~~~~~~~
1 error generated.

**Comment by anoopcs9** [comment]
You'll have to install development packages for RADOS library i.e, _librados-devel_ or _librados-dev_ as mentioned in the [Install](https://github.com/ceph/go-ceph#installation) section of README.

**Comment by itxiaolin** [comment]
I have installed the ceph library, and I can see the rados header files in the /opt/homebrew/include directory

<img width="741" alt="image" src="https://github.com/ceph/go-ceph/assets/66697106/0c1c5e43-5089-4e4d-868e-409374efff2a">

**Comment by itxiaolin** [comment]
Yes, macos M1 is installed by default in /opt/homebrew/include and /opt/homebrew/lib, while go-ceph only looks from /usr/local/lib and /usr/local/include.

sudo ln -s /opt/homebrew/Cellar/ceph-client/17.2.5_1/include/rados  /usr/local/include/rados
sudo ln -s /opt/homebrew/Cellar/ceph-client/17.2.5_1/include/rbd  /usr/local/include/rbd
sudo ln -s /opt/homebrew/Cellar/ceph-client/17.2.5_1/include/cephfs  /usr/local/include/cephfs
sudo ln -s /opt/homebrew/Cellar/ceph-client/17.2.5_1/include/radosstriper  /usr/local/include/radosstriper

sudo ln -s /opt/homebrew/Cellar/ceph-client/17.2.5_1/lib/libceph-common.2.dylib /usr/local/lib/libceph-common.2.dylib
sudo ln -s /opt/homebrew/Cellar/ceph-client/17.2.5_1/lib/libceph-common.dylib /usr/local/lib/libceph-common.dylib
sudo ln -s /opt/homebrew/Cellar/ceph-client/17.2.5_1/lib/libcephfs.2.0.0.dylib /usr/local/lib/libcephfs.2.0.0.dylib
sudo ln -s /opt/homebrew/Cellar/ceph-client/17.2.5_1/lib/libcephfs.2.dylib /usr/local/lib/libcephfs.2.dylib
sudo ln -s /opt/homebrew/Cellar/ceph-client/17.2.5_1/lib/libcephfs.dylib /usr/local/lib/libcephfs.dylib
sudo ln -s /opt/homebrew/Cellar/ceph-client/17.2.5_1/lib/librados.2.0.0.dylib /usr/local/lib/librados.2.0.0.dylib
sudo ln -s /opt/homebrew/Cellar/ceph-client/17.2.5_1/lib/librados.2.dylib /usr/local/lib/librados.2.dylib
sudo ln -s /opt/homebrew/Cellar/ceph-client/17.2.5_1/lib/librados.dylib /usr/local/lib/librados.dylib
sudo ln -s /opt/homebrew/Cellar/ceph-client/17.2.5_1/lib/libradosstriper.1.0.0.dylib /usr/local/lib/libradosstriper.1.0.0.dylib
sudo ln -s /opt/homebrew/Cellar/ceph-client/17.2.5_1/lib/libradosstriper.1.dylib /usr/local/lib/libradosstriper.1.dylib
sudo ln -s /opt/homebrew/Cellar/ceph-client/17.2.5_1/lib/libradosstriper.dylib /usr/local/lib/libradosstriper.dylib
sudo ln -s /opt/homebrew/Cellar/ceph-client/17.2.5_1/lib/librbd.1.17.0.dylib /usr/local/lib/librbd.1.17.0.dylib
sudo ln -s /opt/homebrew/Cellar/ceph-client/17.2.5_1/lib/librbd.1.dylib /usr/local/lib/librbd.1.dylib
sudo ln -s /opt/homebrew/Cellar/ceph-client/17.2.5_1/lib/librbd.dylib /usr/local/lib/librbd.dylib

**Comment by itxiaolin** [comment]
The above problem can be solved by soft connections to /usr/local/lib and /usr/local/include

**Comment by anoopcs9** [comment]
> I tried to use 'export CGO_LDFLAGS="-L/opt/homebrew/lib"' to solve my problem. Although I could build, I would still get an error when running. Show 'ceph - 17.2.5 / build/lib/librados. 2. The dylib' (no to file) '

I see that you set `CGO_LDFLAGS` to `-L/opt/homebrew/lib/`. Are you sure that required shared libraries are present under _/opt/homebrew/lib/_?

**Comment by itxiaolin** [comment]
Yes, macos M1 series architecture, shared libraries in /opt/homebrew/lib/
<img width="492" alt="image" src="https://github.com/ceph/go-ceph/assets/66697106/48909807-db98-4511-b9a7-22bab163e363">

**Comment by ansiwen** [comment]
Try `otool -L [your executable]` to find out, if it can find the libraries at runtime.

**Comment by stryan** [comment]
Similar issue occurred for me. I was able to get my executable to run successfully without symlinks by building with
```
export CGO_CFLAGS=-I/opt/homebrew/include
export CGO_LDFLAGS="-L/opt/homebrew/lib"
```
and running with
`DYLD_FALLBACK_LIBRARY_PATH=/opt/homebrew/lib ./ceph_tests`

For reference, otool output:
```
ceph_tests:
        /opt/homebrew/opt/ceph-client/lib/librados.2.dylib (compatibility version 2.0.0, current version 2.0.0)
        /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1953.255.0)
        /usr/lib/libresolv.9.dylib (compatibility version 1.0.0, current version 1.0.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1319.0.0)
```
and original runtime error:
```
dyld[40480]: Library not loaded: '@rpath/libceph-common.2.dylib'
  Referenced from: '/opt/homebrew/Cellar/ceph-client/17.2.5_1/lib/librados.2.0.0.dylib'
  Reason: tried: '/usr/local/lib/libceph-common.2.dylib' (no such file), '/usr/lib/libceph-common.2.dylib' (no such file)
[2]    40480 abort      ./ceph_tests`
```

**Comment by anoopcs9** [comment]
@itxiaolin Were you able to make any progress with suggestions from https://github.com/ceph/go-ceph/issues/902#issuecomment-1632472200 and https://github.com/ceph/go-ceph/issues/902#issuecomment-1644182874?
