### ISSUE TITLE
rgw: Empty usage problem

### ISSUE THREAD

**Issue by TheMoti** [ceph/go-ceph#919]
Hello ceph team,

Recently I encountered an issue getting bucket stats from our Ceph cluster, in which there were some really old empty buckets from Nautilus version with an empty usage field (in recent versions empty buckets do have the usage object, just with zero values for fields; but these old ones were like empty empty). Since [```Usage```](https://github.com/ceph/go-ceph/blob/master/rgw/admin/bucket.go#L30) struct is nested in ``Bucket`` struct, I couldn't find any access to the definition neither to compare it with ```Usage{}``` (``==nil`` does not work) nor to create and assign a zero usage object for these ancient bucket stats. I ended up checking the usage fields being null, which works, but is really not a good way to do it. I was wondering if there's any way you can handle these empty usages while unmarshal-ing bucket stats; If not, would you mind suggesting some workaround for this case?

Regards

**Comment by phlogistonjohn** [comment]
@anoopcs9 @thotz any thoughts?

**Comment by TheMoti** [comment]
Update: Apparently it happens in new versions too. I tested _aws-cli_ and _python_ clients with a ceph cluster v16, and still newly created buckets had empty usage objects; So I was wrong about buckets being old and it should happen a lot more frequently.
