### ISSUE TITLE
cut out a  go-ceph release

### ISSUE THREAD

**Issue by Madhu-1** [ceph/go-ceph#92]
This will be helpful in ceph-csi if we want to consume the go-ceph library.
if we imported a released version tag (we are kind of safe. as a released branch is not  frequently updated)

importing master in ceph-csi branch won't be a good idea as it can break anytime (due to merging for new PR's)

**Comment by Madhu-1** [comment]
CC @noahdesu

**Comment by noahdesu** [comment]
yeh, we can definitely do this. how about if we take the current master and fork it off into `release-0.1` and tag a v0.1.0 release? i'm open to other suggestions too.

**Comment by Madhu-1** [comment]
@noahdesu works for me :+1:

**Comment by humblec** [comment]
> yeh, we can definitely do this. how about if we take the current master and fork it off into `release-0.1` and tag a v0.1.0 release? i'm open to other suggestions too.

If we are confident enough we can call it as `v1.0.0` @noahdesu

**Comment by isi-lincoln** [comment]
Same issue as #75 .  I'm fine with closing that one in place of this one.

**Comment by phlogistonjohn** [comment]
The initial "0.2" release is currently planned for 2020-02-11.

**Comment by phlogistonjohn** [comment]
https://github.com/ceph/go-ceph/releases/tag/v0.2.0
Please open new issues for anything pertaining to the release content or process itself. Thanks!
