### ISSUE TITLE
Support bucket scope quota

### ISSUE THREAD

**Issue by R4scal** [ceph/go-ceph#931]
Hello. 

For now `SetUserQuota` method forces QuotaType to `user`, but api support `bucket` option [doc](https://docs.ceph.com/en/latest/radosgw/adminops/#set-bucket-quota)

```
// SetUserQuota sets quota to a user
// Global quotas (https://docs.ceph.com/en/latest/radosgw/admin/#reading-writing-global-quotas) are not surfaced in the Admin Ops API
// So this library cannot expose it yet
func (api *API) SetUserQuota(ctx context.Context, quota QuotaSpec) error {
	// Always for quota type to user
	quota.QuotaType = "user"
```

Are there any reasons not to remove this restriction in the library?

**Comment by phlogistonjohn** [comment]
cc @thotz @anoopcs9

**Comment by thotz** [comment]
More like not implemented till now, no specific reason for that. In other words, for OBC use case we need to implement the user quota. It was not necessary at that point. Feel free to contribute bucket quotas apis @R4scal
