### ISSUE TITLE
monCommand not support "osd find osd.0"?

### ISSUE THREAD

**Issue by lifa1225** [ceph/go-ceph#96]
I want to get information about the location of OSD.
I can get information by executing on the command line "ceph osd find osd.0".
But when I send prefix("osd find osd.0") to this function("monCommand") in golang,the info is not what I want.
Is there a solution?Thanks!

**Comment by tchaikov** [comment]
```go
	command, err := json.Marshal(
                map[string]interface{}{"prefix": "osd find", "id": 0})
	assert.NoError(suite.T(), err)

	buf, info, err := suite.conn.MonCommand(command)
```
please note, "osd find" is the prefix. while `0` is the parameter whose name is "id".

**Comment by lifa1225** [comment]
> could you try
> 
> ```go
> 	command, err := json.Marshal(
>                 map[string]interface{}{"prefix": "osd find", "id": 0})
> 	assert.NoError(suite.T(), err)
> 
> 	buf, info, err := suite.conn.MonCommand(command)
> ```
> 
> ?
> please note, "osd find" is the prefix. while `0` is the parameter whose name is "id".

It works!Thanks for your answer!
