### ISSUE TITLE
Build error on ioctx_octopus.go even will using -tags

### ISSUE THREAD

**Issue by rishidhupar** [ceph/go-ceph#999]
Hi,

I am running into an issue when building go-ceph when using `golang:1.22-bullseye` docker base image.  I am using go-ceph v0.28.0.

```
root@d3cbf0ccd5ac:/src# go version
go version go1.22.4 linux/amd64
root@d3cbf0ccd5ac:/src# cat /etc/debian_version 
11.9
root@d3cbf0ccd5ac:/src# apt list --installed | grep -E 'rbd|rados'

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

librados-dev/now 14.2.21-1 amd64 [installed,local]
librados2/now 14.2.21-1 amd64 [installed,local]
librbd-dev/now 14.2.21-1 amd64 [installed,local]
librbd1/now 14.2.21-1 amd64 [installed,local]
```

Here is the actual error when trying to build. I would think that by selecting tags of `quincy` this octopus release file wouldn't be compiled. 
```
root@d3cbf0ccd5ac:/src# go build -tags quincy
# github.com/ceph/go-ceph/rados
/go/pkg/mod/github.com/ceph/go-ceph@v0.28.0/rados/ioctx_octopus.go:25:2: could not determine kind of name for C.rados_set_pool_full_try
/go/pkg/mod/github.com/ceph/go-ceph@v0.28.0/rados/ioctx_octopus.go:38:2: could not determine kind of name for C.rados_unset_pool_full_try
```

**Comment by phlogistonjohn** [comment]
According to https://docs.ceph.com/en/latest/releases/ Ceph 14 was Nautilus.

They way our build tags work is inclusive of older versions. So if you use build tag "pacific" you'd get all features that were added in pacific and prior (octopus, nautilus, etc...) . Build tag "quincy" includes all new features for quincy + pacific (and prior).

So choosing "quincy" will not exclude features that were added in "octopus". You can try using the nautilus build tag. We still test it - but as I note in #648, not for long*.

* We're not planning on removing the tag, just cease testing. But you know what that leads to. :-)

**Comment by phlogistonjohn** [comment]
I should also note that these days I try to discourage folks from naming files after ceph releases. But we were not aware of the confusion that can sometimes cause at the time the file in question was added.

**Comment by rishidhupar** [comment]
Thanks for the help. I advanced the librbd and librados libraries on my build image to Quincy (which is the Ceph version we are using) and was able to build just fine.
